/**
 * Runtime Configuration Loader
 *
 * Implements 12-factor app "Config in Environment" principle.
 * Configuration is loaded at runtime from /config.json generated by Docker entrypoint,
 * allowing the same Docker image to work across all environments.
 *
 * Pattern: Client-only SPA (SSR disabled via +layout.ts)
 * - Browser: Fetches /config.json (generated by docker-entrypoint.sh)
 * - Validation: Enforces schema in production (fail hard on misconfiguration)
 * - Dev fallback: Only when dev=true, never in staging/prod
 */

import { browser, dev } from '$app/environment';
import { z } from 'zod';

export interface RuntimeConfig {
	API_BASE_URL: string;
	AUTH_URL: string;
}

const ConfigSchema = z.object({
	API_BASE_URL: z.string().url().min(1, 'API_BASE_URL must be a valid URL'),
	AUTH_URL: z.string().url().min(1, 'AUTH_URL must be a valid URL'),
});

// Development fallback configuration (only used when dev=true)
const DEV_CONFIG: RuntimeConfig = {
	API_BASE_URL: 'http://localhost:3017',
	AUTH_URL: 'http://localhost:3001',
};

let cachedConfig: RuntimeConfig | null = null;
let configPromise: Promise<RuntimeConfig> | null = null;

/**
 * Load runtime configuration from /config.json
 * Uses caching to avoid multiple fetches
 */
async function loadConfig(): Promise<RuntimeConfig> {
	// Guard: SSR should never happen (we disabled it in +layout.ts)
	if (!browser) {
		if (dev) {
			console.warn('[Clock] Config accessed during SSR in dev mode, using fallback');
			return DEV_CONFIG;
		}
		throw new Error('[Clock] Runtime config called on server - SSR should be disabled');
	}

	// Return cached config if available
	if (cachedConfig) {
		return cachedConfig;
	}

	// If already loading, return the existing promise
	if (configPromise) {
		return configPromise;
	}

	// Fetch config from /config.json (generated by docker-entrypoint.sh)
	configPromise = fetch('/config.json')
		.then((res) => {
			if (!res.ok) {
				if (dev) {
					console.warn(
						`[Clock] Failed to load /config.json (HTTP ${res.status}), using dev defaults`
					);
					return DEV_CONFIG;
				}
				throw new Error(
					`[Clock] Failed to load /config.json (HTTP ${res.status}) - check Docker entrypoint script`
				);
			}
			return res.json();
		})
		.then((config) => {
			// Validate schema in production (fail hard on misconfiguration)
			if (!dev) {
				const result = ConfigSchema.safeParse(config);
				if (!result.success) {
					throw new Error(
						`[Clock] Invalid config.json schema: ${result.error.errors.map((e) => `${e.path.join('.')}: ${e.message}`).join(', ')}`
					);
				}
			}

			cachedConfig = config as RuntimeConfig;
			return cachedConfig;
		});

	return configPromise;
}

/**
 * Get the full runtime configuration
 */
export async function getConfig(): Promise<RuntimeConfig> {
	return loadConfig();
}

/**
 * Get the Auth service URL
 */
export async function getAuthUrl(): Promise<string> {
	const config = await getConfig();
	return config.AUTH_URL;
}

/**
 * Get the API base URL
 */
export async function getApiBaseUrl(): Promise<string> {
	const config = await getConfig();
	return config.API_BASE_URL;
}

/**
 * Initialize runtime configuration
 * Call this early in app lifecycle (e.g., +layout.svelte onMount)
 */
export async function initializeConfig(): Promise<void> {
	await loadConfig();
}
