export const EDITOR_CONFIG = {
	AUTO_SAVE_DELAY: 3000,
	NEW_DOC_SAVE_DELAY: 2000,
	MIN_CONTENT_LENGTH: 50,
	DEBOUNCE_DELAY: 300,
	SAVE_LOCK_TIMEOUT: 30000,
	LOCAL_STORAGE_KEYS: {
		BACKUP_PREFIX: 'doc_backup_',
		DRAFT_PREFIX: 'doc_draft_',
	},
};
