/**
 * Unified Dexie Database — Single IndexedDB for all ManaCore apps.
 *
 * All collections from all app modules are registered in one database.
 * Table names that collide across apps are prefixed (e.g., pictureTags, storageTags).
 *
 * The SYNC_APP_MAP maps each table back to its appId for sync routing.
 */

import Dexie, { type EntityTable } from 'dexie';

// ─── Database ──────────────────────────────────────────────

export const db = new Dexie('manacore');

db.version(1).stores({
	// ─── Sync Infrastructure ───
	_pendingChanges: '++id, appId, collection, recordId, createdAt',
	_syncMeta: '[appId+collection]',

	// ─── Core / ManaCore (appId: 'manacore') ───
	userSettings: 'id, key',
	dashboardConfigs: 'id',

	// ─── Todo (appId: 'todo') ───
	tasks:
		'id, dueDate, isCompleted, priority, order, projectId, [isCompleted+order], [projectId+order]',
	todoProjects: 'id, order, isArchived, isDefault',
	taskLabels: 'id, taskId, labelId', // junction to globalTags (labelId = tagId)
	reminders: 'id, taskId',
	boardViews: 'id, order, groupBy',

	// ─── Calendar (appId: 'calendar') ───
	calendars: 'id, isDefault, isVisible',
	events: 'id, calendarId, startDate, endDate, allDay, [calendarId+startDate]',

	// ─── Contacts (appId: 'contacts') ───
	contacts: 'id, firstName, lastName, email, company, isFavorite, isArchived',

	// ─── Chat (appId: 'chat') ───
	conversations: 'id, isArchived, isPinned, spaceId, templateId',
	messages: 'id, conversationId, sender, [conversationId+sender]',
	chatTemplates: 'id, isDefault',

	// ─── Picture (appId: 'picture') ───
	images: 'id, isFavorite, isPublic, archivedAt, prompt',
	boards: 'id, isPublic',
	boardItems: 'id, boardId, itemType, zIndex, [boardId+zIndex]',
	imageTags: 'id, imageId, tagId, [imageId+tagId]', // junction to globalTags

	// ─── Cards (appId: 'cards') ───
	cardDecks: 'id, isPublic',
	cards: 'id, deckId, difficulty, nextReview, order, [deckId+order]',

	// ─── Zitare (appId: 'zitare') ───
	zitareFavorites: 'id, quoteId',
	zitareLists: 'id',

	// ─── Mukke (appId: 'mukke') ───
	songs: 'id, artist, album, genre, favorite, title',
	mukkePlaylists: 'id, name',
	playlistSongs: 'id, playlistId, songId, sortOrder, [playlistId+sortOrder]',
	mukkeProjects: 'id, title, songId',
	markers: 'id, beatId, type, sortOrder',

	// ─── Storage (appId: 'storage') ───
	files: 'id, parentFolderId, mimeType, isFavorite, isDeleted, name',
	storageFolders: 'id, parentFolderId, path, depth, isFavorite, isDeleted',
	fileTags: 'id, fileId, tagId, [fileId+tagId]', // junction to globalTags

	// ─── Presi (appId: 'presi') ───
	presiDecks: 'id, isPublic',
	slides: 'id, deckId, order, [deckId+order]',

	// ─── Inventar (appId: 'inventar') ───
	invCollections: 'id, order, templateId',
	invItems: 'id, collectionId, locationId, categoryId, status, name, [collectionId+order]',
	invLocations: 'id, parentId, path, depth, order',
	invCategories: 'id, parentId, order',

	// ─── Photos (appId: 'photos') ───
	albums: 'id, isAutoGenerated, name',
	albumItems: 'id, albumId, mediaId, sortOrder, [albumId+sortOrder]',
	photoFavorites: 'id, mediaId',
	photoMediaTags: 'id, mediaId, tagId, [mediaId+tagId]', // junction to globalTags

	// ─── SkillTree (appId: 'skilltree') ───
	skills: 'id, branch, parentId, level',
	activities: 'id, skillId, timestamp',
	achievements: 'id, key, unlockedAt',

	// ─── CityCorners (appId: 'citycorners') ───
	cities: 'id, slug, country, name',
	ccLocations: 'id, cityId, category, name',
	ccFavorites: 'id, locationId',

	// ─── Times (appId: 'times') ───
	timeClients: 'id, order, isArchived, shortCode',
	timeProjects: 'id, clientId, isArchived, isBillable, guildId, visibility, order',
	timeEntries:
		'id, projectId, clientId, date, isRunning, [date+projectId], [date+clientId], guildId, visibility',
	timeTemplates: 'id, usageCount, lastUsedAt, projectId',
	timeSettings: 'id',
	timeAlarms: 'id, enabled, time',
	timeCountdownTimers: 'id, status',
	timeWorldClocks: 'id, sortOrder, timezone',

	// ─── Context (appId: 'context') ───
	contextSpaces: 'id, pinned, prefix',
	documents: 'id, spaceId, type, pinned, title, [spaceId+type]',

	// ─── Questions (appId: 'questions') ───
	qCollections: 'id, sortOrder, isDefault',
	questions: 'id, collectionId, status, priority, [collectionId+status]',
	answers: 'id, questionId, isAccepted',

	// ─── NutriPhi (appId: 'nutriphi') ───
	meals: 'id, date, mealType, [date+mealType]',
	goals: 'id',
	nutriFavorites: 'id, mealType, usageCount',

	// ─── Planta (appId: 'planta') ───
	plants: 'id, isActive, healthStatus',
	plantPhotos: 'id, plantId, isPrimary, [plantId+isPrimary]',
	wateringSchedules: 'id, plantId, nextWateringAt',
	wateringLogs: 'id, plantId, wateredAt',

	// ─── uLoad (appId: 'uload') ───
	links: 'id, shortCode, isActive, folderId, order, clickCount, [folderId+order], [isActive+order]',
	uloadFolders: 'id, order',
	linkTags: 'id, linkId, tagId, [linkId+tagId]',

	// ─── Calc (appId: 'calc') ───
	calculations: 'id, mode',
	savedFormulas: 'id, mode, name',

	// ─── Moodlit (appId: 'moodlit') ───
	moods: 'id, name, animation, isDefault',
	sequences: 'id, name',

	// ─── Memoro (appId: 'memoro') ───
	memos: 'id, processingStatus, isArchived, isPinned, language, [isArchived+createdAt]',
	memories: 'id, memoId',
	memoTags: 'id, memoId, tagId', // junction to globalTags
	memoroSpaces: 'id, ownerId',
	spaceMembers: 'id, spaceId, userId',
	memoSpaces: 'id, memoId, spaceId',

	// ─── Guides (appId: 'guides') ───
	guides: 'id, category, difficulty, collectionId, tags',
	sections: 'id, guideId, order',
	steps: 'id, guideId, sectionId, order, [guideId+order]',
	guideCollections: 'id',
	runs: 'id, guideId, startedAt, completedAt',

	// ─── Playground (appId: 'playground') ───
	// No persistent data — stateless LLM playground

	// ─── Shared: Global Tags (appId: 'tags') ───
	globalTags: 'id, name, groupId',
	tagGroups: 'id',

	// ─── Shared: Links (appId: 'links') ───
	manaLinks: 'id, sourceAppId, sourceRecordId, targetAppId, targetRecordId',
});

// ─── Sync App Map ──────────────────────────────────────────
// Maps each table to its appId for sync routing.
// The SyncEngine uses this to group pending changes and push to /sync/{appId}.

export const SYNC_APP_MAP: Record<string, string[]> = {
	manacore: ['userSettings', 'dashboardConfigs'],
	todo: ['tasks', 'todoProjects', 'taskLabels', 'reminders', 'boardViews'],
	calendar: ['calendars', 'events'],
	contacts: ['contacts'],
	chat: ['conversations', 'messages', 'chatTemplates'],
	picture: ['images', 'boards', 'boardItems', 'imageTags'],
	cards: ['cardDecks', 'cards'],
	zitare: ['zitareFavorites', 'zitareLists'],
	mukke: ['songs', 'mukkePlaylists', 'playlistSongs', 'mukkeProjects', 'markers'],
	storage: ['files', 'storageFolders', 'fileTags'],
	presi: ['presiDecks', 'slides'],
	inventar: ['invCollections', 'invItems', 'invLocations', 'invCategories'],
	photos: ['albums', 'albumItems', 'photoFavorites', 'photoMediaTags'],
	skilltree: ['skills', 'activities', 'achievements'],
	citycorners: ['cities', 'ccLocations', 'ccFavorites'],
	times: [
		'timeClients',
		'timeProjects',
		'timeEntries',
		'timeTemplates',
		'timeSettings',
		'timeAlarms',
		'timeCountdownTimers',
		'timeWorldClocks',
	],
	context: ['contextSpaces', 'documents'],
	questions: ['qCollections', 'questions', 'answers'],
	nutriphi: ['meals', 'goals', 'nutriFavorites'],
	planta: ['plants', 'plantPhotos', 'wateringSchedules', 'wateringLogs'],
	uload: ['links', 'uloadFolders', 'linkTags'],
	calc: ['calculations', 'savedFormulas'],
	moodlit: ['moods', 'sequences'],
	memoro: ['memos', 'memories', 'memoTags', 'memoroSpaces', 'spaceMembers', 'memoSpaces'],
	guides: ['guides', 'sections', 'steps', 'guideCollections', 'runs'],
	tags: ['globalTags', 'tagGroups'],
	links: ['manaLinks'],
};

// ─── Reverse Map: Table → AppId ────────────────────────────
// Used by _pendingChanges to determine which appId to tag a change with.

export const TABLE_TO_APP: Record<string, string> = Object.fromEntries(
	Object.entries(SYNC_APP_MAP).flatMap(([appId, tables]) => tables.map((table) => [table, appId]))
);

// ─── Table Name Mapping (Unified ↔ Backend) ──────────────────
// The unified DB renames tables to avoid collisions (e.g., todoProjects, cardDecks).
// The backend (mana-sync) knows the original names from standalone apps.

/** Unified table name → backend collection name (only renamed tables). */
export const TABLE_TO_SYNC_NAME: Record<string, string> = {
	// todo
	todoProjects: 'projects',
	// chat
	chatTemplates: 'templates',
	// picture
	// cards
	cardDecks: 'decks',
	// zitare
	zitareFavorites: 'favorites',
	zitareLists: 'lists',
	// mukke
	mukkePlaylists: 'playlists',
	mukkeProjects: 'projects',
	// storage
	storageFolders: 'folders',
	// presi
	presiDecks: 'decks',
	// inventar
	invCollections: 'collections',
	invItems: 'items',
	invLocations: 'locations',
	invCategories: 'categories',
	// photos
	photoFavorites: 'favorites',
	photoMediaTags: 'photoTags',
	// citycorners
	ccLocations: 'locations',
	ccFavorites: 'favorites',
	// times
	timeClients: 'clients',
	timeProjects: 'projects',
	timeTemplates: 'templates',
	timeSettings: 'settings',
	timeAlarms: 'alarms',
	timeCountdownTimers: 'countdownTimers',
	timeWorldClocks: 'worldClocks',
	// context
	contextSpaces: 'spaces',
	// questions
	qCollections: 'collections',
	// nutriphi
	nutriFavorites: 'favorites',
	// memoro
	memoroSpaces: 'spaces',
	// uload
	uloadFolders: 'folders',
	// guides
	guideCollections: 'collections',
	// shared: tags
	globalTags: 'tags',
	tagGroups: 'tagGroups',
	// shared: links
	manaLinks: 'links',
};

/** Get the backend collection name for a unified table. */
export function toSyncName(tableName: string): string {
	return TABLE_TO_SYNC_NAME[tableName] ?? tableName;
}

/** Build reverse map: for a given appId, maps backend collection name → unified table name. */
export const SYNC_NAME_TO_TABLE: Record<string, Record<string, string>> = {};
for (const [appId, tables] of Object.entries(SYNC_APP_MAP)) {
	const map: Record<string, string> = {};
	for (const tableName of tables) {
		const syncName = toSyncName(tableName);
		map[syncName] = tableName;
	}
	SYNC_NAME_TO_TABLE[appId] = map;
}

/** Get the unified table name for a backend collection + appId. */
export function fromSyncName(appId: string, syncCollection: string): string {
	return SYNC_NAME_TO_TABLE[appId]?.[syncCollection] ?? syncCollection;
}

// ─── Change Tracking via Dexie Hooks ─────────────────────────
// Automatically records pending changes for every write to sync-relevant tables.
// This means module stores (taskTable.add(), etc.) don't need manual trackChange() calls.

let _applyingServerChanges = false;

/** Set to true while applying server changes to prevent sync loops. */
export function setApplyingServerChanges(v: boolean): void {
	_applyingServerChanges = v;
}

const pendingChangesTable = db.table('_pendingChanges');

for (const [appId, tables] of Object.entries(SYNC_APP_MAP)) {
	for (const tableName of tables) {
		const table = db.table(tableName);

		table.hook('creating', function (_primKey, obj) {
			if (_applyingServerChanges) return;
			const now = new Date().toISOString();
			pendingChangesTable.add({
				appId,
				collection: tableName,
				recordId: obj.id,
				op: 'insert',
				data: { ...obj },
				createdAt: now,
			});
		});

		table.hook('updating', function (modifications, primKey) {
			if (_applyingServerChanges) return;
			const now = new Date().toISOString();
			const fields: Record<string, { value: unknown; updatedAt: string }> = {};
			for (const [key, value] of Object.entries(modifications)) {
				if (key === 'id') continue;
				fields[key] = { value, updatedAt: now };
			}
			pendingChangesTable.add({
				appId,
				collection: tableName,
				recordId: primKey as string,
				op: (modifications as Record<string, unknown>).deletedAt ? 'delete' : 'update',
				fields,
				deletedAt: (modifications as Record<string, unknown>).deletedAt as string | undefined,
				createdAt: now,
			});
		});
	}
}
