/**
 * Unified Dexie Database — Single IndexedDB for all ManaCore apps.
 *
 * All collections from all app modules are registered in one database.
 * Table names that collide across apps are prefixed (e.g., pictureTags, storageTags).
 *
 * The SYNC_APP_MAP maps each table back to its appId for sync routing.
 */

import Dexie, { type EntityTable } from 'dexie';

// ─── Database ──────────────────────────────────────────────

export const db = new Dexie('manacore');

db.version(1).stores({
	// ─── Sync Infrastructure ───
	_pendingChanges: '++id, appId, collection, recordId, createdAt',
	_syncMeta: '[appId+collection]',

	// ─── Core / ManaCore (appId: 'manacore') ───
	userSettings: 'id, key',
	dashboardConfigs: 'id',

	// ─── Todo (appId: 'todo') ───
	tasks:
		'id, dueDate, isCompleted, priority, order, projectId, [isCompleted+order], [projectId+order]',
	todoProjects: 'id, order, isArchived, isDefault',
	labels: 'id',
	taskLabels: 'id, taskId, labelId',
	reminders: 'id, taskId',
	boardViews: 'id, order, groupBy',

	// ─── Calendar (appId: 'calendar') ───
	calendars: 'id, isDefault, isVisible',
	events: 'id, calendarId, startDate, endDate, allDay, [calendarId+startDate]',

	// ─── Contacts (appId: 'contacts') ───
	contacts: 'id, firstName, lastName, email, company, isFavorite, isArchived',

	// ─── Chat (appId: 'chat') ───
	conversations: 'id, isArchived, isPinned, spaceId, templateId',
	messages: 'id, conversationId, sender, [conversationId+sender]',
	chatTemplates: 'id, isDefault',

	// ─── Picture (appId: 'picture') ───
	images: 'id, isFavorite, isPublic, archivedAt, prompt',
	boards: 'id, isPublic',
	boardItems: 'id, boardId, itemType, zIndex, [boardId+zIndex]',
	pictureTags: 'id, name',
	imageTags: 'id, imageId, tagId, [imageId+tagId]',

	// ─── Cards (appId: 'cards') ───
	cardDecks: 'id, isPublic',
	cards: 'id, deckId, difficulty, nextReview, order, [deckId+order]',

	// ─── Zitare (appId: 'zitare') ───
	zitareFavorites: 'id, quoteId',
	zitareLists: 'id',

	// ─── Clock (appId: 'clock') ───
	alarms: 'id, enabled, time',
	timers: 'id, status',
	worldClocks: 'id, sortOrder, timezone',

	// ─── Mukke (appId: 'mukke') ───
	songs: 'id, artist, album, genre, favorite, title',
	mukkePlaylists: 'id, name',
	playlistSongs: 'id, playlistId, songId, sortOrder, [playlistId+sortOrder]',
	mukkeProjects: 'id, title, songId',
	markers: 'id, beatId, type, sortOrder',

	// ─── Storage (appId: 'storage') ───
	files: 'id, parentFolderId, mimeType, isFavorite, isDeleted, name',
	storageFolders: 'id, parentFolderId, path, depth, isFavorite, isDeleted',
	storageTags: 'id, name',
	fileTags: 'id, fileId, tagId, [fileId+tagId]',

	// ─── Presi (appId: 'presi') ───
	presiDecks: 'id, isPublic',
	slides: 'id, deckId, order, [deckId+order]',

	// ─── Inventar (appId: 'inventar') ───
	invCollections: 'id, order, templateId',
	invItems: 'id, collectionId, locationId, categoryId, status, name, [collectionId+order]',
	invLocations: 'id, parentId, path, depth, order',
	invCategories: 'id, parentId, order',

	// ─── Photos (appId: 'photos') ───
	albums: 'id, isAutoGenerated, name',
	albumItems: 'id, albumId, mediaId, sortOrder, [albumId+sortOrder]',
	photoFavorites: 'id, mediaId',
	photoTags: 'id, name',
	photoMediaTags: 'id, mediaId, tagId, [mediaId+tagId]',

	// ─── SkillTree (appId: 'skilltree') ───
	skills: 'id, branch, parentId, level',
	activities: 'id, skillId, timestamp',
	achievements: 'id, key, unlockedAt',

	// ─── CityCorners (appId: 'citycorners') ───
	cities: 'id, slug, country, name',
	ccLocations: 'id, cityId, category, name',
	ccFavorites: 'id, locationId',

	// ─── Times (appId: 'times') ───
	timeClients: 'id, order, isArchived, shortCode',
	timeProjects: 'id, clientId, isArchived, isBillable, guildId, visibility, order',
	timeEntries:
		'id, projectId, clientId, date, isRunning, [date+projectId], [date+clientId], guildId, visibility',
	timeTags: 'id, name, order',
	timeTemplates: 'id, usageCount, lastUsedAt, projectId',
	timeSettings: 'id',

	// ─── Context (appId: 'context') ───
	contextSpaces: 'id, pinned, prefix',
	documents: 'id, spaceId, type, pinned, title, [spaceId+type]',

	// ─── Questions (appId: 'questions') ───
	qCollections: 'id, sortOrder, isDefault',
	questions: 'id, collectionId, status, priority, [collectionId+status]',
	answers: 'id, questionId, isAccepted',

	// ─── NutriPhi (appId: 'nutriphi') ───
	meals: 'id, date, mealType, [date+mealType]',
	goals: 'id',
	nutriFavorites: 'id, mealType, usageCount',

	// ─── Planta (appId: 'planta') ───
	plants: 'id, isActive, healthStatus',
	plantPhotos: 'id, plantId, isPrimary, [plantId+isPrimary]',
	wateringSchedules: 'id, plantId, nextWateringAt',
	wateringLogs: 'id, plantId, wateredAt',

	// ─── uLoad (appId: 'uload') ───
	links: 'id, shortCode, isActive, folderId, order, clickCount, [folderId+order], [isActive+order]',
	uloadTags: 'id, slug, name',
	uloadFolders: 'id, order',
	linkTags: 'id, linkId, tagId, [linkId+tagId]',

	// ─── Calc (appId: 'calc') ───
	calculations: 'id, mode',
	savedFormulas: 'id, mode, name',

	// ─── Moodlit (appId: 'moodlit') ───
	moods: 'id, name, animation, isDefault',
	sequences: 'id, name',

	// ─── Memoro (appId: 'memoro') ───
	memos: 'id, processingStatus, isArchived, isPinned, language, [isArchived+createdAt]',
	memories: 'id, memoId',
	memoroTags: 'id, name, sortOrder',
	memoTags: 'id, memoId, tagId',
	memoroSpaces: 'id, ownerId',
	spaceMembers: 'id, spaceId, userId',
	memoSpaces: 'id, memoId, spaceId',

	// ─── Guides (appId: 'guides') ───
	guides: 'id, category, difficulty, collectionId, tags',
	sections: 'id, guideId, order',
	steps: 'id, guideId, sectionId, order, [guideId+order]',
	guideCollections: 'id',
	runs: 'id, guideId, startedAt, completedAt',

	// ─── Playground (appId: 'playground') ───
	// No persistent data — stateless LLM playground

	// ─── Shared: Global Tags (appId: 'tags') ───
	globalTags: 'id, name, groupId',
	tagGroups: 'id',

	// ─── Shared: Links (appId: 'links') ───
	manaLinks: 'id, sourceAppId, sourceRecordId, targetAppId, targetRecordId',
});

// ─── Sync App Map ──────────────────────────────────────────
// Maps each table to its appId for sync routing.
// The SyncEngine uses this to group pending changes and push to /sync/{appId}.

export const SYNC_APP_MAP: Record<string, string[]> = {
	manacore: ['userSettings', 'dashboardConfigs'],
	todo: ['tasks', 'todoProjects', 'labels', 'taskLabels', 'reminders', 'boardViews'],
	calendar: ['calendars', 'events'],
	contacts: ['contacts'],
	chat: ['conversations', 'messages', 'chatTemplates'],
	picture: ['images', 'boards', 'boardItems', 'pictureTags', 'imageTags'],
	cards: ['cardDecks', 'cards'],
	zitare: ['zitareFavorites', 'zitareLists'],
	clock: ['alarms', 'timers', 'worldClocks'],
	mukke: ['songs', 'mukkePlaylists', 'playlistSongs', 'mukkeProjects', 'markers'],
	storage: ['files', 'storageFolders', 'storageTags', 'fileTags'],
	presi: ['presiDecks', 'slides'],
	inventar: ['invCollections', 'invItems', 'invLocations', 'invCategories'],
	photos: ['albums', 'albumItems', 'photoFavorites', 'photoTags', 'photoMediaTags'],
	skilltree: ['skills', 'activities', 'achievements'],
	citycorners: ['cities', 'ccLocations', 'ccFavorites'],
	times: [
		'timeClients',
		'timeProjects',
		'timeEntries',
		'timeTags',
		'timeTemplates',
		'timeSettings',
	],
	context: ['contextSpaces', 'documents'],
	questions: ['qCollections', 'questions', 'answers'],
	nutriphi: ['meals', 'goals', 'nutriFavorites'],
	planta: ['plants', 'plantPhotos', 'wateringSchedules', 'wateringLogs'],
	uload: ['links', 'uloadTags', 'uloadFolders', 'linkTags'],
	calc: ['calculations', 'savedFormulas'],
	moodlit: ['moods', 'sequences'],
	memoro: [
		'memos',
		'memories',
		'memoroTags',
		'memoTags',
		'memoroSpaces',
		'spaceMembers',
		'memoSpaces',
	],
	guides: ['guides', 'sections', 'steps', 'guideCollections', 'runs'],
	tags: ['globalTags', 'tagGroups'],
	links: ['manaLinks'],
};

// ─── Reverse Map: Table → AppId ────────────────────────────
// Used by _pendingChanges to determine which appId to tag a change with.

export const TABLE_TO_APP: Record<string, string> = Object.fromEntries(
	Object.entries(SYNC_APP_MAP).flatMap(([appId, tables]) => tables.map((table) => [table, appId]))
);
