/**
 * Unified Dexie Database — Single IndexedDB for all ManaCore apps.
 *
 * All collections from all app modules are registered in one database.
 * Table names that collide across apps are prefixed (e.g., pictureTags, storageTags).
 *
 * The SYNC_APP_MAP maps each table back to its appId for sync routing.
 */

import Dexie, { type EntityTable } from 'dexie';
import { trackFirstContent } from '$lib/stores/funnel-tracking';
import { fire as fireTrigger } from '$lib/triggers/registry';
import { checkInlineSuggestion } from '$lib/triggers/inline-suggest';

// ─── Database ──────────────────────────────────────────────

export const db = new Dexie('manacore');

db.version(1).stores({
	// ─── Sync Infrastructure ───
	_pendingChanges: '++id, appId, collection, recordId, createdAt',
	_syncMeta: '[appId+collection]',

	// ─── Core / ManaCore (appId: 'manacore') ───
	userSettings: 'id, key',
	dashboardConfigs: 'id',
	automations: 'id, sourceApp, targetApp, enabled, [sourceApp+sourceCollection]',

	// ─── Todo (appId: 'todo') ───
	tasks:
		'id, dueDate, isCompleted, priority, order, projectId, [isCompleted+order], [projectId+order]',
	todoProjects: 'id, order, isArchived, isDefault',
	taskLabels: 'id, taskId, labelId', // junction to globalTags (labelId = tagId)
	reminders: 'id, taskId',
	boardViews: 'id, order, groupBy',

	// ─── Calendar (appId: 'calendar') ───
	calendars: 'id, isDefault, isVisible',
	events: 'id, calendarId, startDate, endDate, allDay, [calendarId+startDate]',
	eventTags: 'id, eventId, tagId, [eventId+tagId]',

	// ─── Contacts (appId: 'contacts') ───
	contacts: 'id, firstName, lastName, email, company, isFavorite, isArchived',
	contactTags: 'id, contactId, tagId, [contactId+tagId]',

	// ─── Chat (appId: 'chat') ───
	conversations: 'id, isArchived, isPinned, spaceId, templateId',
	messages: 'id, conversationId, sender, [conversationId+sender]',
	chatTemplates: 'id, isDefault',
	conversationTags: 'id, conversationId, tagId, [conversationId+tagId]',

	// ─── Picture (appId: 'picture') ───
	images: 'id, isFavorite, isPublic, isArchived, prompt',
	boards: 'id, isPublic',
	boardItems: 'id, boardId, itemType, zIndex, [boardId+zIndex]',
	imageTags: 'id, imageId, tagId, [imageId+tagId]', // junction to globalTags

	// ─── Cards (appId: 'cards') ───
	cardDecks: 'id, isPublic',
	cards: 'id, deckId, difficulty, nextReview, order, [deckId+order]',
	deckTags: 'id, deckId, tagId, [deckId+tagId]',

	// ─── Zitare (appId: 'zitare') ───
	zitareFavorites: 'id, quoteId',
	zitareLists: 'id',
	zitareListTags: 'id, listId, tagId, [listId+tagId]',

	// ─── Music (appId: 'music') ───
	songs: 'id, artist, album, genre, favorite, title',
	mukkePlaylists: 'id, name',
	playlistSongs: 'id, playlistId, songId, sortOrder, [playlistId+sortOrder]',
	mukkeProjects: 'id, title, songId',
	markers: 'id, beatId, type, sortOrder',
	songTags: 'id, songId, tagId, [songId+tagId]',

	// ─── Storage (appId: 'storage') ───
	files: 'id, parentFolderId, mimeType, isFavorite, isDeleted, name',
	storageFolders: 'id, parentFolderId, path, depth, isFavorite, isDeleted',
	fileTags: 'id, fileId, tagId, [fileId+tagId]', // junction to globalTags

	// ─── Presi (appId: 'presi') ───
	presiDecks: 'id, isPublic',
	slides: 'id, deckId, order, [deckId+order]',
	presiDeckTags: 'id, deckId, tagId, [deckId+tagId]',

	// ─── Inventar (appId: 'inventar') ───
	invCollections: 'id, order, templateId',
	invItems: 'id, collectionId, locationId, categoryId, status, name, [collectionId+order]',
	invLocations: 'id, parentId, path, depth, order',
	invCategories: 'id, parentId, order',
	invItemTags: 'id, itemId, tagId, [itemId+tagId]',

	// ─── Photos (appId: 'photos') ───
	albums: 'id, isAutoGenerated, name',
	albumItems: 'id, albumId, mediaId, sortOrder, [albumId+sortOrder]',
	photoFavorites: 'id, mediaId',
	photoMediaTags: 'id, mediaId, tagId, [mediaId+tagId]', // junction to globalTags

	// ─── SkillTree (appId: 'skilltree') ───
	skills: 'id, branch, parentId, level',
	activities: 'id, skillId, timestamp',
	achievements: 'id, key, unlockedAt',
	skillTags: 'id, skillId, tagId, [skillId+tagId]',

	// ─── CityCorners (appId: 'citycorners') ───
	cities: 'id, slug, country, name',
	ccLocations: 'id, cityId, category, name',
	ccFavorites: 'id, locationId',
	ccLocationTags: 'id, locationId, tagId, [locationId+tagId]',

	// ─── Times (appId: 'times') ───
	timeClients: 'id, order, isArchived, shortCode',
	timeProjects: 'id, clientId, isArchived, isBillable, guildId, visibility, order',
	timeEntries:
		'id, projectId, clientId, date, isRunning, [date+projectId], [date+clientId], guildId, visibility',
	timeTemplates: 'id, usageCount, lastUsedAt, projectId',
	timeSettings: 'id',
	timeAlarms: 'id, enabled, time',
	timeCountdownTimers: 'id, status',
	timeWorldClocks: 'id, sortOrder, timezone',
	entryTags: 'id, entryId, tagId, [entryId+tagId]',

	// ─── Context (appId: 'context') ───
	contextSpaces: 'id, pinned, prefix',
	documents: 'id, spaceId, type, pinned, title, [spaceId+type]',
	documentTags: 'id, documentId, tagId, [documentId+tagId]',

	// ─── Questions (appId: 'questions') ───
	qCollections: 'id, sortOrder, isDefault',
	questions: 'id, collectionId, status, priority, [collectionId+status]',
	answers: 'id, questionId, isAccepted',
	questionTags: 'id, questionId, tagId, [questionId+tagId]',

	// ─── NutriPhi (appId: 'nutriphi') ───
	meals: 'id, date, mealType, [date+mealType]',
	goals: 'id',
	nutriFavorites: 'id, mealType, usageCount',
	mealTags: 'id, mealId, tagId, [mealId+tagId]',

	// ─── Planta (appId: 'planta') ───
	plants: 'id, isActive, healthStatus',
	plantPhotos: 'id, plantId, isPrimary, [plantId+isPrimary]',
	wateringSchedules: 'id, plantId, nextWateringAt',
	wateringLogs: 'id, plantId, wateredAt',
	plantTags: 'id, plantId, tagId, [plantId+tagId]',

	// ─── uLoad (appId: 'uload') ───
	links: 'id, shortCode, isActive, folderId, order, clickCount, [folderId+order], [isActive+order]',
	uloadTags: 'id, slug, name',
	uloadFolders: 'id, order',
	linkTags: 'id, linkId, tagId, [linkId+tagId]',

	// ─── Calc (appId: 'calc') ───
	calculations: 'id, mode',
	savedFormulas: 'id, mode, name',

	// ─── Moodlit (appId: 'moodlit') ───
	moods: 'id, name, animation, isDefault',
	sequences: 'id, name',
	moodTags: 'id, moodId, tagId, [moodId+tagId]',

	// ─── Memoro (appId: 'memoro') ───
	memos: 'id, processingStatus, isArchived, isPinned, language, [isArchived+createdAt]',
	memories: 'id, memoId',
	memoTags: 'id, memoId, tagId', // junction to globalTags
	memoroSpaces: 'id, ownerId',
	spaceMembers: 'id, spaceId, userId',
	memoSpaces: 'id, memoId, spaceId',

	// ─── Guides (appId: 'guides') ───
	guides: 'id, category, difficulty, collectionId, tags',
	sections: 'id, guideId, order',
	steps: 'id, guideId, sectionId, order, [guideId+order]',
	guideCollections: 'id',
	runs: 'id, guideId, startedAt, completedAt',
	guideTags: 'id, guideId, tagId, [guideId+tagId]',

	// ─── Playground (appId: 'playground') ───
	// No persistent data — stateless LLM playground

	// ─── Habits (appId: 'habits') ───
	habits: 'id, order, isArchived, color',
	habitLogs: 'id, habitId, timestamp, [habitId+timestamp]',

	// ─── Notes (appId: 'notes') ───
	notes: 'id, isPinned, isArchived, color, title, updatedAt',
	noteTags: 'id, noteId, tagId, [noteId+tagId]',

	// ─── Finance (appId: 'finance') ───
	transactions: 'id, type, categoryId, date, amount, [date+type], [categoryId+date]',
	financeCategories: 'id, type, order',
	budgets: 'id, categoryId, month, [month+categoryId]',

	// ─── Places (appId: 'places') ───
	places: 'id, name, category, isFavorite, isArchived, latitude, longitude',
	locationLogs: 'id, placeId, timestamp, [placeId+timestamp]',
	placeTags: 'id, placeId, tagId, [placeId+tagId]',

	// ─── Shared: Global Tags (appId: 'tags') ───
	globalTags: 'id, name, groupId',
	tagGroups: 'id',

	// ─── Shared: Links (appId: 'links') ───
	manaLinks: 'id, sourceAppId, sourceRecordId, targetAppId, targetRecordId',
});

// ─── Schema Migrations ────────────────────────────────────────
// Version 2: Habits emoji → icon field migration

const EMOJI_TO_ICON: Record<string, string> = {
	'\u2615': 'coffee',
	'\ud83d\udeb6': 'person-simple-walk',
	'\ud83c\udfc3': 'person-simple-run',
	'\ud83e\uddd8': 'person-simple-tai-chi',
	'\ud83d\udca7': 'drop',
	'\ud83c\udf4e': 'apple-logo',
	'\ud83d\udcda': 'book-open',
	'\ud83d\udcaa': 'barbell',
	'\ud83d\udecc': 'bed',
	'\ud83c\udfb5': 'music-note',
	'\ud83d\udc8a': 'pill',
	'\ud83c\udf7a': 'beer-stein',
	'\ud83c\udf55': 'pizza',
	'\ud83d\udeb4': 'bicycle',
	'\ud83d\udcdd': 'pencil-simple',
	'\ud83e\uddfc': 'tooth',
	'\u2b50': 'star',
	'\ud83d\ude2e\u200d\ud83d\udca8': 'wind',
};

db.version(2)
	.stores({})
	.upgrade((tx) => {
		return tx
			.table('habits')
			.toCollection()
			.modify((habit: Record<string, unknown>) => {
				if (habit.emoji !== undefined && habit.icon === undefined) {
					habit.icon = EMOJI_TO_ICON[habit.emoji as string] ?? 'star';
					delete habit.emoji;
				}
			});
	});

// ─── Version 3: Unified Time Model (timeBlocks) ─────────────
// Adds timeBlocks table, updates indexes on events/timeEntries/tasks/habitLogs,
// and migrates existing time data into timeBlocks.

db.version(3)
	.stores({
		// New tables
		timeBlocks:
			'id, startDate, kind, type, sourceModule, sourceId, [sourceModule+sourceId], [type+startDate], [kind+startDate]',
		timeBlockTags: 'id, blockId, tagId, [blockId+tagId]',

		// Updated indexes (timeBlockId / scheduledBlockId added)
		events: 'id, calendarId, timeBlockId',
		timeEntries: 'id, projectId, clientId, timeBlockId, guildId, visibility',
		tasks:
			'id, dueDate, isCompleted, priority, order, projectId, scheduledBlockId, [isCompleted+order], [projectId+order]',
		habitLogs: 'id, habitId, timeBlockId, [habitId+timeBlockId]',
	})
	.upgrade(async (tx) => {
		const timeBlocksTable = tx.table('timeBlocks');

		// 1. Migrate calendar events → timeBlocks
		const events = await tx.table('events').toArray();
		for (const event of events) {
			if (!event.startDate) continue;
			const blockId = crypto.randomUUID();
			await timeBlocksTable.add({
				id: blockId,
				startDate: event.startDate,
				endDate: event.endDate ?? null,
				allDay: event.allDay ?? false,
				isLive: false,
				timezone: null,
				recurrenceRule: event.recurrenceRule ?? null,
				kind: 'scheduled',
				type: 'event',
				sourceModule: 'calendar',
				sourceId: event.id,
				linkedBlockId: null,
				title: event.title ?? '',
				description: event.description ?? null,
				color: event.color ?? null,
				icon: null,
				projectId: null,
				createdAt: event.createdAt ?? new Date().toISOString(),
				updatedAt: event.updatedAt ?? new Date().toISOString(),
				deletedAt: event.deletedAt ?? null,
			});
			await tx.table('events').update(event.id, { timeBlockId: blockId });
		}

		// 2. Migrate time entries → timeBlocks
		const entries = await tx.table('timeEntries').toArray();
		for (const entry of entries) {
			if (!entry.date && !entry.startTime) continue; // skip entries with no date at all
			const blockId = crypto.randomUUID();
			const startDate = entry.startTime ?? `${entry.date}T00:00:00.000Z`;
			await timeBlocksTable.add({
				id: blockId,
				startDate,
				endDate: entry.endTime ?? null,
				allDay: false,
				isLive: entry.isRunning ?? false,
				timezone: null,
				recurrenceRule: null,
				kind: 'logged',
				type: 'timeEntry',
				sourceModule: 'times',
				sourceId: entry.id,
				linkedBlockId: null,
				title: entry.description || 'Time Entry',
				description: null,
				color: null,
				icon: null,
				projectId: entry.projectId ?? null,
				createdAt: entry.createdAt ?? new Date().toISOString(),
				updatedAt: entry.updatedAt ?? new Date().toISOString(),
				deletedAt: entry.deletedAt ?? null,
			});
			await tx.table('timeEntries').update(entry.id, { timeBlockId: blockId });
		}

		// 3. Migrate habit logs → timeBlocks
		const logs = await tx.table('habitLogs').toArray();
		const habitsById = new Map<string, Record<string, unknown>>();
		const allHabits = await tx.table('habits').toArray();
		for (const h of allHabits) habitsById.set(h.id as string, h);

		for (const log of logs) {
			if (!log.timestamp) continue;
			const blockId = crypto.randomUUID();
			const habit = habitsById.get(log.habitId as string);
			await timeBlocksTable.add({
				id: blockId,
				startDate: log.timestamp,
				endDate: null,
				allDay: false,
				isLive: false,
				timezone: null,
				recurrenceRule: null,
				kind: 'logged',
				type: 'habit',
				sourceModule: 'habits',
				sourceId: log.id,
				linkedBlockId: null,
				title: (habit?.title as string) ?? 'Habit',
				description: null,
				color: (habit?.color as string) ?? null,
				icon: (habit?.icon as string) ?? null,
				projectId: null,
				createdAt: log.createdAt ?? new Date().toISOString(),
				updatedAt: log.updatedAt ?? log.createdAt ?? new Date().toISOString(),
				deletedAt: log.deletedAt ?? null,
			});
			await tx.table('habitLogs').update(log.id, { timeBlockId: blockId });
		}

		// 4. Migrate scheduled tasks → timeBlocks
		const tasks = await tx.table('tasks').toArray();
		for (const task of tasks) {
			if (!task.scheduledDate) continue;
			const blockId = crypto.randomUUID();
			const startISO = task.scheduledStartTime
				? `${task.scheduledDate}T${task.scheduledStartTime}:00`
				: `${task.scheduledDate}T09:00:00`;
			const durationMs = task.estimatedDuration ? task.estimatedDuration * 1000 : 3600000; // default 1h
			const endISO = new Date(new Date(startISO).getTime() + durationMs).toISOString();

			await timeBlocksTable.add({
				id: blockId,
				startDate: startISO,
				endDate: endISO,
				allDay: !task.scheduledStartTime,
				isLive: false,
				timezone: null,
				recurrenceRule: null,
				kind: 'scheduled',
				type: 'task',
				sourceModule: 'todo',
				sourceId: task.id,
				linkedBlockId: null,
				title: task.title ?? '',
				description: null,
				color: null,
				icon: null,
				projectId: task.projectId ?? null,
				createdAt: task.createdAt ?? new Date().toISOString(),
				updatedAt: task.updatedAt ?? new Date().toISOString(),
				deletedAt: task.deletedAt ?? null,
			});
			await tx.table('tasks').update(task.id, { scheduledBlockId: blockId });
		}
	});

// ─── Sync App Map ──────────────────────────────────────────
// Maps each table to its appId for sync routing.
// The SyncEngine uses this to group pending changes and push to /sync/{appId}.

export const SYNC_APP_MAP: Record<string, string[]> = {
	manacore: ['userSettings', 'dashboardConfigs', 'automations'],
	todo: ['tasks', 'todoProjects', 'taskLabels', 'reminders', 'boardViews'],
	calendar: ['calendars', 'events', 'eventTags'],
	contacts: ['contacts', 'contactTags'],
	chat: ['conversations', 'messages', 'chatTemplates', 'conversationTags'],
	picture: ['images', 'boards', 'boardItems', 'imageTags'],
	cards: ['cardDecks', 'cards', 'deckTags'],
	zitare: ['zitareFavorites', 'zitareLists', 'zitareListTags'],
	music: ['songs', 'mukkePlaylists', 'playlistSongs', 'mukkeProjects', 'markers', 'songTags'],
	storage: ['files', 'storageFolders', 'fileTags'],
	presi: ['presiDecks', 'slides', 'presiDeckTags'],
	inventar: ['invCollections', 'invItems', 'invLocations', 'invCategories', 'invItemTags'],
	photos: ['albums', 'albumItems', 'photoFavorites', 'photoMediaTags'],
	skilltree: ['skills', 'activities', 'achievements', 'skillTags'],
	citycorners: ['cities', 'ccLocations', 'ccFavorites', 'ccLocationTags'],
	times: [
		'timeClients',
		'timeProjects',
		'timeEntries',
		'timeTemplates',
		'timeSettings',
		'timeAlarms',
		'timeCountdownTimers',
		'timeWorldClocks',
		'entryTags',
	],
	context: ['contextSpaces', 'documents', 'documentTags'],
	questions: ['qCollections', 'questions', 'answers', 'questionTags'],
	nutriphi: ['meals', 'goals', 'nutriFavorites', 'mealTags'],
	planta: ['plants', 'plantPhotos', 'wateringSchedules', 'wateringLogs', 'plantTags'],
	uload: ['links', 'uloadTags', 'uloadFolders', 'linkTags'],
	calc: ['calculations', 'savedFormulas'],
	moodlit: ['moods', 'sequences', 'moodTags'],
	memoro: ['memos', 'memories', 'memoTags', 'memoroSpaces', 'spaceMembers', 'memoSpaces'],
	guides: ['guides', 'sections', 'steps', 'guideCollections', 'runs', 'guideTags'],
	habits: ['habits', 'habitLogs'],
	notes: ['notes', 'noteTags'],
	finance: ['transactions', 'financeCategories', 'budgets'],
	places: ['places', 'locationLogs', 'placeTags'],
	tags: ['globalTags', 'tagGroups'],
	links: ['manaLinks'],
	timeblocks: ['timeBlocks', 'timeBlockTags'],
};

// ─── Reverse Map: Table → AppId ────────────────────────────
// Used by _pendingChanges to determine which appId to tag a change with.

export const TABLE_TO_APP: Record<string, string> = Object.fromEntries(
	Object.entries(SYNC_APP_MAP).flatMap(([appId, tables]) => tables.map((table) => [table, appId]))
);

// ─── Table Name Mapping (Unified ↔ Backend) ──────────────────
// The unified DB renames tables to avoid collisions (e.g., todoProjects, cardDecks).
// The backend (mana-sync) knows the original names from standalone apps.

/** Unified table name → backend collection name (only renamed tables). */
export const TABLE_TO_SYNC_NAME: Record<string, string> = {
	// todo
	todoProjects: 'projects',
	// chat
	chatTemplates: 'templates',
	// picture
	// cards
	cardDecks: 'decks',
	// zitare
	zitareFavorites: 'favorites',
	zitareLists: 'lists',
	// music
	mukkePlaylists: 'playlists',
	mukkeProjects: 'projects',
	// storage
	storageFolders: 'folders',
	// presi
	presiDecks: 'decks',
	// inventar
	invCollections: 'collections',
	invItems: 'items',
	invLocations: 'locations',
	invCategories: 'categories',
	// photos
	photoFavorites: 'favorites',
	photoMediaTags: 'photoTags',
	// citycorners
	ccLocations: 'locations',
	ccFavorites: 'favorites',
	// times
	timeClients: 'clients',
	timeProjects: 'projects',
	timeTemplates: 'templates',
	timeSettings: 'settings',
	timeAlarms: 'alarms',
	timeCountdownTimers: 'countdownTimers',
	timeWorldClocks: 'worldClocks',
	// context
	contextSpaces: 'spaces',
	// questions
	qCollections: 'collections',
	// nutriphi
	nutriFavorites: 'favorites',
	// memoro
	memoroSpaces: 'spaces',
	// uload
	uloadTags: 'tags',
	uloadFolders: 'folders',
	// guides
	guideCollections: 'collections',
	// finance
	financeCategories: 'categories',
	// shared: tags
	globalTags: 'tags',
	tagGroups: 'tagGroups',
	// shared: links
	manaLinks: 'links',
};

/** Get the backend collection name for a unified table. */
export function toSyncName(tableName: string): string {
	return TABLE_TO_SYNC_NAME[tableName] ?? tableName;
}

/** Build reverse map: for a given appId, maps backend collection name → unified table name. */
export const SYNC_NAME_TO_TABLE: Record<string, Record<string, string>> = {};
for (const [appId, tables] of Object.entries(SYNC_APP_MAP)) {
	const map: Record<string, string> = {};
	for (const tableName of tables) {
		const syncName = toSyncName(tableName);
		map[syncName] = tableName;
	}
	SYNC_NAME_TO_TABLE[appId] = map;
}

/** Get the unified table name for a backend collection + appId. */
export function fromSyncName(appId: string, syncCollection: string): string {
	return SYNC_NAME_TO_TABLE[appId]?.[syncCollection] ?? syncCollection;
}

// ─── Change Tracking via Dexie Hooks ─────────────────────────
// Automatically records pending changes for every write to sync-relevant tables.
// This means module stores (taskTable.add(), etc.) don't need manual trackChange() calls.

let _applyingServerChanges = false;

/** Set to true while applying server changes to prevent sync loops. */
export function setApplyingServerChanges(v: boolean): void {
	_applyingServerChanges = v;
}

const pendingChangesTable = db.table('_pendingChanges');

for (const [appId, tables] of Object.entries(SYNC_APP_MAP)) {
	for (const tableName of tables) {
		const table = db.table(tableName);

		table.hook('creating', function (_primKey, obj) {
			if (_applyingServerChanges) return;
			const now = new Date().toISOString();
			pendingChangesTable.add({
				appId,
				collection: tableName,
				recordId: obj.id,
				op: 'insert',
				data: { ...obj },
				createdAt: now,
			});
			trackFirstContent(appId);
			fireTrigger(appId, tableName, 'insert', { ...obj });
			// Defer cross-table reads outside the Dexie hook's transaction scope
			const objCopy = { ...obj };
			setTimeout(() => {
				checkInlineSuggestion(appId, tableName, objCopy).then((sug) => {
					if (sug)
						window.dispatchEvent(new CustomEvent('mana:automation-suggest', { detail: sug }));
				});
			}, 0);
		});

		table.hook('updating', function (modifications, primKey) {
			if (_applyingServerChanges) return;
			const now = new Date().toISOString();
			const fields: Record<string, { value: unknown; updatedAt: string }> = {};
			for (const [key, value] of Object.entries(modifications)) {
				if (key === 'id') continue;
				fields[key] = { value, updatedAt: now };
			}
			pendingChangesTable.add({
				appId,
				collection: tableName,
				recordId: primKey as string,
				op: (modifications as Record<string, unknown>).deletedAt ? 'delete' : 'update',
				fields,
				deletedAt: (modifications as Record<string, unknown>).deletedAt as string | undefined,
				createdAt: now,
			});
			const op = (modifications as Record<string, unknown>).deletedAt ? 'delete' : 'update';
			fireTrigger(appId, tableName, op, modifications as Record<string, unknown>);
		});
	}
}
