export enum StoryError {
	CREATE_CHARACTERS = 'CREATE_CHARACTERS',
	CREATE_STORYLINE = 'CREATE_STORYLINE',
	GENERATE_STORY_TITLE = 'GENERATE_STORY_TITLE',
	GENERATE_STORY_ILLUSTRATION = 'GENERATE_STORY_ILLUSTRATION',
	GENERATE_STORY_ILLUSTRATION_PROMPTS = 'GENERATE_STORY_ILLUSTRATION_PROMPTS',
	GENERATE_STORY_BOOK_ILLUSTRATION = 'GENERATE_STORY_BOOK_ILLUSTRATION',
	GENERATE_STORY_BOOK_TITLE = 'GENERATE_STORY_BOOK_TITLE',
	GENERATE_STORY_BOOK = 'GENERATE_STORY_BOOK',
	TRANSLATE_STORY_TO_GERMAN = 'TRANSLATE_STORY_TO_GERMAN',
}
