/**
 * Albums Store — Local-First with Dexie.js
 *
 * All reads and writes go to IndexedDB first.
 * When authenticated, changes sync to the server in the background.
 */

import {
	albumCollection,
	albumItemCollection,
	type LocalAlbum,
	type LocalAlbumItem,
} from '$lib/data/local-store';
import { PhotosEvents } from '@manacore/shared-utils/analytics';
import type { Album, Photo } from '@photos/shared';

// State
let albums = $state<Album[]>([]);
let currentAlbum = $state<Album | null>(null);
let albumPhotos = $state<Photo[]>([]);
let loading = $state(false);
let error = $state<string | null>(null);

function toAlbum(local: LocalAlbum): Album {
	return {
		id: local.id,
		userId: 'local',
		name: local.name,
		description: local.description ?? undefined,
		coverMediaId: local.coverMediaId ?? undefined,
		isAutoGenerated: local.isAutoGenerated,
		autoGenerateType: local.autoGenerateType ?? undefined,
		autoGenerateValue: local.autoGenerateValue ?? undefined,
		createdAt: local.createdAt ?? new Date().toISOString(),
		updatedAt: local.updatedAt ?? new Date().toISOString(),
	} as Album;
}

async function refreshAlbums() {
	const localAlbums = await albumCollection.getAll();
	albums = localAlbums.map(toAlbum);
}

export const albumStore = {
	get albums() {
		return albums;
	},
	get currentAlbum() {
		return currentAlbum;
	},
	get albumPhotos() {
		return albumPhotos;
	},
	get loading() {
		return loading;
	},
	get error() {
		return error;
	},

	async loadAlbums() {
		loading = true;
		error = null;
		try {
			await refreshAlbums();
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load albums';
		} finally {
			loading = false;
		}
	},

	async loadAlbum(id: string) {
		loading = true;
		error = null;
		try {
			const local = await albumCollection.get(id);
			if (local) {
				currentAlbum = toAlbum(local);
				// Load album items (media IDs)
				const items = await albumItemCollection.getAll();
				const albumItems = items
					.filter((item) => item.albumId === id)
					.sort((a, b) => a.sortOrder - b.sortOrder);
				// Album items reference mediaIds — photo data comes from mana-media
				albumPhotos = albumItems.map((item) => ({ id: item.mediaId }) as Photo);
			} else {
				currentAlbum = null;
				albumPhotos = [];
			}
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load album';
		} finally {
			loading = false;
		}
	},

	async createAlbum(data: { name: string; description?: string }) {
		error = null;
		try {
			const newLocal: LocalAlbum = {
				id: crypto.randomUUID(),
				name: data.name,
				description: data.description ?? null,
				coverMediaId: null,
				isAutoGenerated: false,
				autoGenerateType: null,
				autoGenerateValue: null,
			};
			const inserted = await albumCollection.insert(newLocal);
			const newAlbum = toAlbum(inserted);
			albums = [...albums, newAlbum];
			PhotosEvents.albumCreated();
			return newAlbum;
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to create album';
			return null;
		}
	},

	async updateAlbum(id: string, data: { name?: string; description?: string }) {
		error = null;
		try {
			const updateData: Partial<LocalAlbum> = {};
			if (data.name !== undefined) updateData.name = data.name;
			if (data.description !== undefined) updateData.description = data.description ?? null;

			const updated = await albumCollection.update(id, updateData);
			if (updated) {
				const updatedAlbum = toAlbum(updated);
				albums = albums.map((a) => (a.id === id ? updatedAlbum : a));
				if (currentAlbum?.id === id) currentAlbum = updatedAlbum;
				return updatedAlbum;
			}
			return null;
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to update album';
			return null;
		}
	},

	async deleteAlbum(id: string) {
		error = null;
		try {
			// Delete album items first
			const items = await albumItemCollection.getAll();
			for (const item of items.filter((i) => i.albumId === id)) {
				await albumItemCollection.delete(item.id);
			}
			await albumCollection.delete(id);
			albums = albums.filter((a) => a.id !== id);
			PhotosEvents.albumDeleted();
			if (currentAlbum?.id === id) {
				currentAlbum = null;
				albumPhotos = [];
			}
			return true;
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to delete album';
			return false;
		}
	},

	async addPhotosToAlbum(albumId: string, mediaIds: string[]) {
		error = null;
		try {
			const existing = await albumItemCollection.getAll();
			const existingInAlbum = existing.filter((i) => i.albumId === albumId);
			let nextOrder = existingInAlbum.length;

			for (const mediaId of mediaIds) {
				// Skip duplicates
				if (existingInAlbum.some((i) => i.mediaId === mediaId)) continue;

				await albumItemCollection.insert({
					id: crypto.randomUUID(),
					albumId,
					mediaId,
					sortOrder: nextOrder++,
				});
			}
			PhotosEvents.photosAddedToAlbum(mediaIds.length);
			if (currentAlbum?.id === albumId) {
				await this.loadAlbum(albumId);
			}
			return true;
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to add photos to album';
			return false;
		}
	},

	async removePhotoFromAlbum(albumId: string, mediaId: string) {
		error = null;
		try {
			const items = await albumItemCollection.getAll();
			const item = items.find((i) => i.albumId === albumId && i.mediaId === mediaId);
			if (item) {
				await albumItemCollection.delete(item.id);
				albumPhotos = albumPhotos.filter((p) => p.id !== mediaId);
				PhotosEvents.photoRemovedFromAlbum();
			}
			return true;
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to remove photo from album';
			return false;
		}
	},

	async setCover(albumId: string, mediaId: string) {
		error = null;
		try {
			const updated = await albumCollection.update(albumId, {
				coverMediaId: mediaId,
			} as Partial<LocalAlbum>);
			if (updated) {
				const updatedAlbum = toAlbum(updated);
				albums = albums.map((a) => (a.id === albumId ? updatedAlbum : a));
				if (currentAlbum?.id === albumId) currentAlbum = updatedAlbum;
			}
			return true;
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to set album cover';
			return false;
		}
	},

	clearCurrentAlbum() {
		currentAlbum = null;
		albumPhotos = [];
	},

	reset() {
		albums = [];
		currentAlbum = null;
		albumPhotos = [];
		loading = false;
		error = null;
	},
};
