/**
 * Albums Store — Mutation-Only
 *
 * Reads are handled by live queries in queries.ts.
 * This store only handles mutations (create, update, delete, add/remove items).
 */

import { albumCollection, albumItemCollection, type LocalAlbum } from '$lib/data/local-store';
import { PhotosEvents } from '@manacore/shared-utils/analytics';
import { toAlbum } from '$lib/data/queries';
import type { Album } from '@photos/shared';

export const albumMutations = {
	async createAlbum(data: { name: string; description?: string }): Promise<Album | null> {
		try {
			const newLocal: LocalAlbum = {
				id: crypto.randomUUID(),
				name: data.name,
				description: data.description ?? null,
				coverMediaId: null,
				isAutoGenerated: false,
				autoGenerateType: null,
				autoGenerateValue: null,
			};
			const inserted = await albumCollection.insert(newLocal);
			PhotosEvents.albumCreated();
			return toAlbum(inserted);
		} catch (e) {
			console.error('Failed to create album:', e);
			return null;
		}
	},

	async updateAlbum(
		id: string,
		data: { name?: string; description?: string }
	): Promise<Album | null> {
		try {
			const updateData: Partial<LocalAlbum> = {};
			if (data.name !== undefined) updateData.name = data.name;
			if (data.description !== undefined) updateData.description = data.description ?? null;

			const updated = await albumCollection.update(id, updateData);
			return updated ? toAlbum(updated) : null;
		} catch (e) {
			console.error('Failed to update album:', e);
			return null;
		}
	},

	async deleteAlbum(id: string): Promise<boolean> {
		try {
			// Delete album items first
			const items = await albumItemCollection.getAll();
			for (const item of items.filter((i) => i.albumId === id)) {
				await albumItemCollection.delete(item.id);
			}
			await albumCollection.delete(id);
			PhotosEvents.albumDeleted();
			return true;
		} catch (e) {
			console.error('Failed to delete album:', e);
			return false;
		}
	},

	async addPhotosToAlbum(albumId: string, mediaIds: string[]): Promise<boolean> {
		try {
			const existing = await albumItemCollection.getAll();
			const existingInAlbum = existing.filter((i) => i.albumId === albumId);
			let nextOrder = existingInAlbum.length;

			for (const mediaId of mediaIds) {
				if (existingInAlbum.some((i) => i.mediaId === mediaId)) continue;

				await albumItemCollection.insert({
					id: crypto.randomUUID(),
					albumId,
					mediaId,
					sortOrder: nextOrder++,
				});
			}
			PhotosEvents.photosAddedToAlbum(mediaIds.length);
			return true;
		} catch (e) {
			console.error('Failed to add photos to album:', e);
			return false;
		}
	},

	async removePhotoFromAlbum(albumId: string, mediaId: string): Promise<boolean> {
		try {
			const items = await albumItemCollection.getAll();
			const item = items.find((i) => i.albumId === albumId && i.mediaId === mediaId);
			if (item) {
				await albumItemCollection.delete(item.id);
				PhotosEvents.photoRemovedFromAlbum();
			}
			return true;
		} catch (e) {
			console.error('Failed to remove photo from album:', e);
			return false;
		}
	},

	async setCover(albumId: string, mediaId: string): Promise<boolean> {
		try {
			await albumCollection.update(albumId, {
				coverMediaId: mediaId,
			} as Partial<LocalAlbum>);
			return true;
		} catch (e) {
			console.error('Failed to set album cover:', e);
			return false;
		}
	},
};
