services:
  postgres:
    image: postgres:16-alpine
    container_name: uload-postgres
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: uload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - uload_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: uload-pgadmin
    restart: unless-stopped
    ports:
      - '5051:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@uload.local
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - uload_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  uload_postgres_data:
  uload_pgadmin_data:
