/**
 * Runtime Configuration for Calendar App
 *
 * 12-Factor Pattern: Configuration is loaded from /config.json at runtime,
 * generated by Docker entrypoint from environment variables.
 * This allows the same Docker image to run in different environments
 * without rebuilding.
 */

import { browser, dev } from '$app/environment';
import { z } from 'zod';

export interface RuntimeConfig {
	BACKEND_URL: string;
	AUTH_URL: string;
}

/**
 * Schema validation for config.json
 * Ensures all required configuration is present and valid
 */
const ConfigSchema = z.object({
	BACKEND_URL: z.string().url().min(1, 'BACKEND_URL must be a valid URL'),
	AUTH_URL: z.string().url().min(1, 'AUTH_URL must be a valid URL'),
});

/**
 * Development defaults - only used when:
 * 1. dev === true (from $app/environment)
 * 2. /config.json fetch fails
 *
 * In production, missing config.json is a deployment error.
 */
const DEV_CONFIG: RuntimeConfig = {
	BACKEND_URL: 'http://localhost:3016',
	AUTH_URL: 'http://localhost:3001',
};

let cachedConfig: RuntimeConfig | null = null;
let configPromise: Promise<RuntimeConfig> | null = null;

/**
 * Load configuration from /config.json
 * Fail-hard in production if config is missing or invalid
 */
async function loadConfig(): Promise<RuntimeConfig> {
	// Guard: SSR should never happen (we disabled it in +layout.ts)
	if (!browser) {
		if (dev) {
			console.warn('[Calendar] Config accessed during SSR in dev mode, using fallback');
			return DEV_CONFIG;
		}
		throw new Error('[Calendar] Runtime config called on server - SSR should be disabled');
	}

	// Return cached config if available
	if (cachedConfig) return cachedConfig;

	// Return existing promise if already loading
	if (configPromise) return configPromise;

	configPromise = fetch('/config.json')
		.then((res) => {
			if (!res.ok) {
				if (dev) {
					console.warn(
						`[Calendar] Failed to load /config.json (HTTP ${res.status}), using dev defaults`
					);
					return DEV_CONFIG;
				}
				throw new Error(
					`[Calendar] Failed to load /config.json (HTTP ${res.status}) - check Docker entrypoint script`
				);
			}
			return res.json();
		})
		.then((config) => {
			// Validate schema in production (fail hard on misconfiguration)
			if (!dev) {
				const result = ConfigSchema.safeParse(config);
				if (!result.success) {
					throw new Error(
						`[Calendar] Invalid config.json schema: ${result.error.errors.map((e) => `${e.path.join('.')}: ${e.message}`).join(', ')}`
					);
				}
			}
			cachedConfig = config as RuntimeConfig;
			return cachedConfig;
		});

	return configPromise;
}

/**
 * Get auth service URL
 */
export async function getAuthUrl(): Promise<string> {
	const config = await loadConfig();
	return config.AUTH_URL;
}

/**
 * Get backend API URL
 */
export async function getBackendUrl(): Promise<string> {
	const config = await loadConfig();
	return config.BACKEND_URL;
}

/**
 * Initialize configuration (call early in app lifecycle)
 * This triggers the config load and caches it for subsequent calls
 */
export async function initializeConfig(): Promise<void> {
	await loadConfig();
}
