import {
	Archive,
	Bell,
	Buildings,
	CalendarBlank,
	CaretDown,
	ChartBar,
	ChatCircle,
	Check,
	CheckCircle,
	CheckSquare,
	Clock,
	Cloud,
	Columns,
	Compass,
	CreditCard,
	File,
	FileText,
	Fire,
	Folder,
	Gear,
	Gift,
	Globe,
	GridFour,
	Heart,
	House,
	Key,
	List,
	MagnifyingGlass,
	Microphone,
	Moon,
	MusicNote,
	MusicNotes,
	Palette,
	Playlist,
	Plus,
	Question,
	Robot,
	Scales,
	ShareFat,
	ShareNetwork,
	Shield,
	SignOut,
	Sparkle,
	Spiral,
	Cards,
	Sun,
	Tag,
	Target,
	Timer,
	Trash,
	Tray,
	Upload,
	User,
	Users,
	Waveform,
	X,
} from '@mana/shared-icons';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const phosphorIcons: Record<string, any> = {
	home: House,
	users: Users,
	user: User,
	tag: Tag,
	heart: Heart,
	settings: Gear,
	chat: ChatCircle,
	'help-circle': Question,
	help: Question,
	'share-2': ShareNetwork,
	bell: Bell,
	clock: Clock,
	timer: Timer,
	target: Target,
	globe: Globe,
	inbox: Tray,
	check: Check,
	checkCircle: CheckCircle,
	'check-square': CheckSquare,
	plus: Plus,
	columns: Columns,
	kanban: Columns,
	mic: Microphone,
	calendar: CalendarBlank,
	folder: Folder,
	archive: Archive,
	upload: Upload,
	music: MusicNote,
	document: File,
	chart: ChartBar,
	'bar-chart-3': ChartBar,
	search: MagnifyingGlass,
	list: List,
	compass: Compass,
	moon: Moon,
	sun: Sun,
	logout: SignOut,
	chevronDown: CaretDown,
	menu: List,
	fire: Fire,
	grid: GridFour,
	gridSmall: GridFour,
	palette: Palette,
	creditCard: CreditCard,
	building: Buildings,
	scale: Scales,
	robot: Robot,
	key: Key,
	shield: Shield,
	gift: Gift,
	'music-notes': MusicNotes,
	playlist: Playlist,
	waveform: Waveform,
	'file-text': FileText,
	sparkle: Sparkle,
	sparkles: Sparkle,
	spiral: Spiral,
	share: ShareFat,
	trash: Trash,
	cloud: Cloud,
	x: X,
	close: X,
	tabs: Cards,
	cards: Cards,
};
