/**
 * Runtime Configuration Loader
 *
 * Implements the 12-factor "config in environment" principle.
 * Loads configuration from /config.json at runtime, allowing the same
 * Docker image to be deployed across dev/staging/prod environments.
 *
 * Pattern: Build once, configure at runtime
 */

import { browser } from '$app/environment';

export interface RuntimeConfig {
	API_BASE_URL: string;
	AUTH_URL: string;
	TODO_API_URL: string;
	CALENDAR_API_URL: string;
	CLOCK_API_URL: string;
	CONTACTS_API_URL: string;
}

// Development fallbacks (only used in local dev, not in Docker)
const DEV_CONFIG: RuntimeConfig = {
	API_BASE_URL: 'http://localhost:5173',
	AUTH_URL: 'http://localhost:3001',
	TODO_API_URL: 'http://localhost:3018',
	CALENDAR_API_URL: 'http://localhost:3016',
	CLOCK_API_URL: 'http://localhost:3017',
	CONTACTS_API_URL: 'http://localhost:3015',
};

let cachedConfig: RuntimeConfig | null = null;
let configPromise: Promise<RuntimeConfig> | null = null;

/**
 * Load runtime configuration from /config.json
 * This file is generated by the Docker entrypoint script from environment variables
 */
async function loadConfig(): Promise<RuntimeConfig> {
	// Server-side: use dev config (SSR doesn't need runtime config)
	if (!browser) {
		return DEV_CONFIG;
	}

	// Return cached config if available
	if (cachedConfig) {
		return cachedConfig;
	}

	// Return existing promise if loading
	if (configPromise) {
		return configPromise;
	}

	// Load config from /config.json
	configPromise = fetch('/config.json')
		.then((res) => {
			if (!res.ok) {
				console.warn('Failed to load /config.json, using dev config');
				return DEV_CONFIG;
			}
			return res.json();
		})
		.then((config: RuntimeConfig) => {
			cachedConfig = config;
			return config;
		})
		.catch((error) => {
			console.warn('Error loading runtime config:', error);
			return DEV_CONFIG;
		});

	return configPromise;
}

/**
 * Get runtime configuration
 * Must be called after app initialization
 */
export async function getConfig(): Promise<RuntimeConfig> {
	return loadConfig();
}

/**
 * Get synchronous config (only use after initialization)
 * Throws if config not loaded yet
 */
export function getConfigSync(): RuntimeConfig {
	if (!cachedConfig) {
		throw new Error('Runtime config not loaded. Call getConfig() first.');
	}
	return cachedConfig;
}

/**
 * Initialize runtime config on app start
 * Call this in your root +layout.svelte
 */
export async function initializeConfig(): Promise<void> {
	await loadConfig();
}

/**
 * Helper to get auth URL (most commonly used)
 */
export async function getAuthUrl(): Promise<string> {
	const config = await getConfig();
	return config.AUTH_URL;
}

/**
 * Helper to get backend URL
 */
export async function getApiBaseUrl(): Promise<string> {
	const config = await getConfig();
	return config.API_BASE_URL;
}
