/**
 * Albums Store — Mutation-Only
 *
 * Reads are handled by live queries in queries.ts.
 * This store handles mutations (create, update, delete, add/remove items).
 */

import { db } from '$lib/data/database';
import type { LocalAlbum, LocalAlbumItem, Album } from '../types';
import { toAlbum } from '../queries';

export const albumMutations = {
	async createAlbum(data: { name: string; description?: string }): Promise<Album | null> {
		try {
			const now = new Date().toISOString();
			const newLocal: LocalAlbum = {
				id: crypto.randomUUID(),
				name: data.name,
				description: data.description ?? null,
				coverMediaId: null,
				isAutoGenerated: false,
				autoGenerateType: null,
				autoGenerateValue: null,
				createdAt: now,
				updatedAt: now,
			};
			await db.table('albums').add(newLocal);
			return toAlbum(newLocal);
		} catch (e) {
			console.error('Failed to create album:', e);
			return null;
		}
	},

	async updateAlbum(
		id: string,
		data: { name?: string; description?: string }
	): Promise<Album | null> {
		try {
			const updateData: Record<string, unknown> = { updatedAt: new Date().toISOString() };
			if (data.name !== undefined) updateData.name = data.name;
			if (data.description !== undefined) updateData.description = data.description ?? null;

			await db.table('albums').update(id, updateData);
			const updated = await db.table<LocalAlbum>('albums').get(id);
			return updated ? toAlbum(updated) : null;
		} catch (e) {
			console.error('Failed to update album:', e);
			return null;
		}
	},

	async deleteAlbum(id: string): Promise<boolean> {
		try {
			const now = new Date().toISOString();
			// Soft-delete album items first
			const items = await db.table<LocalAlbumItem>('albumItems').toArray();
			for (const item of items.filter((i) => i.albumId === id)) {
				await db.table('albumItems').update(item.id, { deletedAt: now, updatedAt: now });
			}
			await db.table('albums').update(id, { deletedAt: now, updatedAt: now });
			return true;
		} catch (e) {
			console.error('Failed to delete album:', e);
			return false;
		}
	},

	async addPhotosToAlbum(albumId: string, mediaIds: string[]): Promise<boolean> {
		try {
			const existing = await db.table<LocalAlbumItem>('albumItems').toArray();
			const existingInAlbum = existing.filter((i) => i.albumId === albumId && !i.deletedAt);
			let nextOrder = existingInAlbum.length;
			const now = new Date().toISOString();

			for (const mediaId of mediaIds) {
				if (existingInAlbum.some((i) => i.mediaId === mediaId)) continue;

				await db.table('albumItems').add({
					id: crypto.randomUUID(),
					albumId,
					mediaId,
					sortOrder: nextOrder++,
					createdAt: now,
					updatedAt: now,
				});
			}
			return true;
		} catch (e) {
			console.error('Failed to add photos to album:', e);
			return false;
		}
	},

	async removePhotoFromAlbum(albumId: string, mediaId: string): Promise<boolean> {
		try {
			const items = await db.table<LocalAlbumItem>('albumItems').toArray();
			const item = items.find(
				(i) => i.albumId === albumId && i.mediaId === mediaId && !i.deletedAt
			);
			if (item) {
				const now = new Date().toISOString();
				await db.table('albumItems').update(item.id, { deletedAt: now, updatedAt: now });
			}
			return true;
		} catch (e) {
			console.error('Failed to remove photo from album:', e);
			return false;
		}
	},

	async setCover(albumId: string, mediaId: string): Promise<boolean> {
		try {
			await db.table('albums').update(albumId, {
				coverMediaId: mediaId,
				updatedAt: new Date().toISOString(),
			});
			return true;
		} catch (e) {
			console.error('Failed to set album cover:', e);
			return false;
		}
	},
};
