import { IsString, IsOptional, IsArray, MaxLength, IsBoolean } from 'class-validator';

export class CreateAlbumDto {
	@IsString()
	@MaxLength(255)
	name: string;

	@IsOptional()
	@IsString()
	description?: string;

	@IsOptional()
	@IsString()
	coverMediaId?: string;
}

export class UpdateAlbumDto {
	@IsOptional()
	@IsString()
	@MaxLength(255)
	name?: string;

	@IsOptional()
	@IsString()
	description?: string;

	@IsOptional()
	@IsString()
	coverMediaId?: string;

	@IsOptional()
	@IsBoolean()
	isAutoGenerated?: boolean;
}

export class AddItemsDto {
	@IsArray()
	@IsString({ each: true })
	mediaIds: string[];
}
