/**
 * Photos — Local-First Data Layer
 *
 * Albums, favorites, and tags stored locally.
 * Photo files remain on mana-media (server-side).
 */

import { createLocalStore, type BaseRecord } from '@manacore/local-store';
import { guestAlbums, guestTags } from './guest-seed';

// ─── Types ──────────────────────────────────────────────────

export interface LocalAlbum extends BaseRecord {
	name: string;
	description?: string | null;
	coverMediaId?: string | null;
	isAutoGenerated: boolean;
	autoGenerateType?: 'date' | 'location' | 'camera' | null;
	autoGenerateValue?: string | null;
}

export interface LocalAlbumItem extends BaseRecord {
	albumId: string;
	mediaId: string;
	sortOrder: number;
}

export interface LocalFavorite extends BaseRecord {
	mediaId: string;
}

export interface LocalTag extends BaseRecord {
	name: string;
	color?: string | null;
}

export interface LocalPhotoTag extends BaseRecord {
	mediaId: string;
	tagId: string;
}

// ─── Store ──────────────────────────────────────────────────

const SYNC_SERVER_URL = import.meta.env.PUBLIC_SYNC_SERVER_URL || 'http://localhost:3050';

export const photosStore = createLocalStore({
	appId: 'photos',
	collections: [
		{
			name: 'albums',
			indexes: ['isAutoGenerated', 'name'],
			guestSeed: guestAlbums,
		},
		{
			name: 'albumItems',
			indexes: ['albumId', 'mediaId', 'sortOrder', '[albumId+sortOrder]'],
		},
		{
			name: 'favorites',
			indexes: ['mediaId'],
		},
		{
			name: 'tags',
			indexes: ['name'],
			guestSeed: guestTags,
		},
		{
			name: 'photoTags',
			indexes: ['mediaId', 'tagId', '[mediaId+tagId]'],
		},
	],
	sync: {
		serverUrl: SYNC_SERVER_URL,
	},
});

// Typed collection accessors
export const albumCollection = photosStore.collection<LocalAlbum>('albums');
export const albumItemCollection = photosStore.collection<LocalAlbumItem>('albumItems');
export const favoriteCollection = photosStore.collection<LocalFavorite>('favorites');
export const tagCollection = photosStore.collection<LocalTag>('tags');
export const photoTagCollection = photosStore.collection<LocalPhotoTag>('photoTags');
