/**
 * Guest seed data for the Photos app.
 *
 * Provides demo albums and tags. Actual photos require mana-media.
 */

import type { LocalAlbum, LocalTag } from './local-store';

export const guestAlbums: LocalAlbum[] = [
	{
		id: 'album-favorites',
		name: 'Favoriten',
		description: 'Deine Lieblingsfotos an einem Ort.',
		isAutoGenerated: false,
	},
];

export const guestTags: LocalTag[] = [
	{
		id: 'tag-nature',
		name: 'Natur',
		color: '#22c55e',
	},
	{
		id: 'tag-people',
		name: 'Menschen',
		color: '#3b82f6',
	},
	{
		id: 'tag-travel',
		name: 'Reisen',
		color: '#f59e0b',
	},
];
