/**
 * Reactive Queries & Pure Helpers for Photos
 *
 * Uses Dexie liveQuery to automatically re-render when IndexedDB changes
 * (local writes, sync updates, other tabs). Components call these hooks
 * at init time; no manual fetch/refresh needed.
 */

import { useLiveQueryWithDefault } from '@manacore/local-store/svelte';
import {
	albumCollection,
	albumItemCollection,
	favoriteCollection,
	type LocalAlbum,
	type LocalAlbumItem,
	type LocalFavorite,
} from './local-store';
import type { Album, AlbumItem } from '@photos/shared';

// ─── Type Converters ───────────────────────────────────────

/** Convert a LocalAlbum (IndexedDB) to the shared Album type. */
export function toAlbum(local: LocalAlbum): Album {
	return {
		id: local.id,
		name: local.name,
		description: local.description ?? undefined,
		coverMediaId: local.coverMediaId ?? undefined,
		isAutoGenerated: local.isAutoGenerated,
		autoGenerateType: local.autoGenerateType ?? undefined,
		autoGenerateValue: local.autoGenerateValue ?? undefined,
		itemCount: 0,
		createdAt: local.createdAt ?? new Date().toISOString(),
		updatedAt: local.updatedAt ?? new Date().toISOString(),
	} as Album;
}

/** Convert a LocalAlbumItem (IndexedDB) to the shared AlbumItem type. */
export function toAlbumItem(local: LocalAlbumItem): AlbumItem {
	return {
		id: local.id,
		albumId: local.albumId,
		mediaId: local.mediaId,
		sortOrder: local.sortOrder,
		addedAt: local.createdAt ?? new Date().toISOString(),
	};
}

// ─── Live Query Hooks (call during component init) ─────────

/** All albums. Auto-updates on any change. */
export function useAllAlbums() {
	return useLiveQueryWithDefault(async () => {
		const locals = await albumCollection.getAll();
		return locals.map(toAlbum);
	}, [] as Album[]);
}

/** All album items. Auto-updates on any change. */
export function useAllAlbumItems() {
	return useLiveQueryWithDefault(async () => {
		const locals = await albumItemCollection.getAll();
		return locals.map(toAlbumItem);
	}, [] as AlbumItem[]);
}

/** All favorite media IDs. Auto-updates on any change. */
export function useAllFavorites() {
	return useLiveQueryWithDefault(async () => {
		const locals = await favoriteCollection.getAll();
		return locals;
	}, [] as LocalFavorite[]);
}

// ─── Pure Album Helpers ────────────────────────────────────

/** Get an album by ID. */
export function getAlbumById(albums: Album[], id: string): Album | undefined {
	return albums.find((a) => a.id === id);
}

/** Get album items for a specific album, sorted by sortOrder. */
export function getAlbumItemsForAlbum(allItems: AlbumItem[], albumId: string): AlbumItem[] {
	return allItems.filter((i) => i.albumId === albumId).sort((a, b) => a.sortOrder - b.sortOrder);
}

/** Get the count of items in an album. */
export function getAlbumItemCount(allItems: AlbumItem[], albumId: string): number {
	return allItems.filter((i) => i.albumId === albumId).length;
}

/** Enrich albums with item counts from album items. */
export function enrichAlbumsWithCounts(albums: Album[], allItems: AlbumItem[]): Album[] {
	return albums.map((album) => ({
		...album,
		itemCount: getAlbumItemCount(allItems, album.id),
	}));
}

// ─── Pure Favorite Helpers ─────────────────────────────────

/** Check if a media ID is favorited. */
export function isFavorited(favorites: LocalFavorite[], mediaId: string): boolean {
	return favorites.some((f) => f.mediaId === mediaId);
}

/** Get the set of favorited media IDs. */
export function getFavoritedMediaIds(favorites: LocalFavorite[]): Set<string> {
	return new Set(favorites.map((f) => f.mediaId));
}
