/**
 * Reactive Queries & Pure Helpers for Photos
 *
 * Uses Dexie liveQuery on the unified DB.
 */

import { useScopedLiveQuery } from '$lib/data/scope/use-scoped-live-query.svelte';
import { deriveUpdatedAt } from '$lib/data/sync';
import { db } from '$lib/data/database';
import { scopedForModule } from '$lib/data/scope';
import type { LocalAlbum, LocalAlbumItem, LocalFavorite, Album, AlbumItem } from './types';

// ─── Type Converters ───────────────────────────────────────

/** Convert a LocalAlbum (IndexedDB) to the Album type. */
export function toAlbum(local: LocalAlbum): Album {
	return {
		id: local.id,
		name: local.name,
		description: local.description ?? undefined,
		coverMediaId: local.coverMediaId ?? undefined,
		isAutoGenerated: local.isAutoGenerated,
		autoGenerateType: local.autoGenerateType ?? undefined,
		autoGenerateValue: local.autoGenerateValue ?? undefined,
		itemCount: 0,
		createdAt: local.createdAt ?? new Date().toISOString(),
		updatedAt: deriveUpdatedAt(local),
	};
}

/** Convert a LocalAlbumItem (IndexedDB) to the AlbumItem type. */
export function toAlbumItem(local: LocalAlbumItem): AlbumItem {
	return {
		id: local.id,
		albumId: local.albumId,
		mediaId: local.mediaId,
		sortOrder: local.sortOrder,
		addedAt: local.createdAt ?? new Date().toISOString(),
	};
}

// ─── Live Query Hooks (call during component init) ─────────

/** All albums. Auto-updates on any change. */
export function useAllAlbums() {
	return useScopedLiveQuery(async () => {
		const locals = await scopedForModule<LocalAlbum, string>('photos', 'albums').toArray();
		return locals.filter((a) => !a.deletedAt).map(toAlbum);
	}, []);
}

/** All album items. Auto-updates on any change. */
export function useAllAlbumItems() {
	return useScopedLiveQuery(async () => {
		const locals = await scopedForModule<LocalAlbumItem, string>('photos', 'albumItems').toArray();
		return locals.filter((i) => !i.deletedAt).map(toAlbumItem);
	}, []);
}

/** All favorites. Auto-updates on any change. */
export function useAllFavorites() {
	return useScopedLiveQuery(async () => {
		const locals = await scopedForModule<LocalFavorite, string>(
			'photos',
			'photoFavorites'
		).toArray();
		return locals.filter((f) => !f.deletedAt);
	}, []);
}

// ─── Pure Album Helpers ────────────────────────────────────

/** Get an album by ID. */
export function getAlbumById(albums: Album[], id: string): Album | undefined {
	return albums.find((a) => a.id === id);
}

/** Get album items for a specific album, sorted by sortOrder. */
export function getAlbumItemsForAlbum(allItems: AlbumItem[], albumId: string): AlbumItem[] {
	return allItems.filter((i) => i.albumId === albumId).sort((a, b) => a.sortOrder - b.sortOrder);
}

/** Get the count of items in an album. */
export function getAlbumItemCount(allItems: AlbumItem[], albumId: string): number {
	return allItems.filter((i) => i.albumId === albumId).length;
}

/** Enrich albums with item counts from album items. */
export function enrichAlbumsWithCounts(albums: Album[], allItems: AlbumItem[]): Album[] {
	return albums.map((album) => ({
		...album,
		itemCount: getAlbumItemCount(allItems, album.id),
	}));
}

// ─── Pure Favorite Helpers ─────────────────────────────────

/** Check if a media ID is favorited. */
export function isFavorited(favorites: LocalFavorite[], mediaId: string): boolean {
	return favorites.some((f) => f.mediaId === mediaId);
}

/** Get the set of favorited media IDs. */
export function getFavoritedMediaIds(favorites: LocalFavorite[]): Set<string> {
	return new Set(favorites.map((f) => f.mediaId));
}
