<!--
  Complexity — workbench-embedded treemap of the codebase.
  Area = LOC, color = git churn. Generated by `pnpm audit:map`.
  Admin-only: hides itself for non-admin users.
-->
<script lang="ts">
	import { authStore } from '$lib/stores/auth.svelte';
	import { ShieldWarning } from '@mana/shared-icons';

	let isAdmin = $derived(authStore.user?.role === 'admin');
	let loadError = $state(false);

	function onError() {
		loadError = true;
	}
</script>

{#if !isAdmin}
	<div class="flex h-full flex-col items-center justify-center gap-3 p-8 text-center">
		<ShieldWarning size={40} class="text-muted-foreground" />
		<h3 class="text-base font-medium">Admin-only</h3>
		<p class="max-w-sm text-sm text-muted-foreground">
			Die Complexity Map ist ein internes Diagnose-Tool und nur für Admin-Nutzer sichtbar.
		</p>
	</div>
{:else}
	<div class="flex h-full flex-col gap-3 p-3">
		<div class="flex items-start justify-between gap-4">
			<div>
				<h2 class="text-sm font-semibold">Codebase Complexity Map</h2>
				<p class="text-xs text-muted-foreground">
					Area = LOC · color = git churn (6 months) · hover for details
				</p>
			</div>
			<a
				href="/admin/complexity"
				class="text-xs px-3 py-1.5 rounded-md border bg-muted/40 hover:bg-muted transition-colors"
				title="Open standalone view"
			>
				Full page →
			</a>
		</div>

		{#if loadError}
			<div
				class="flex flex-1 items-center justify-center rounded-md border border-amber-500/30 bg-amber-500/5 p-6 text-sm"
			>
				<div>
					<p class="font-medium text-amber-700 dark:text-amber-300">Map nicht generiert.</p>
					<p class="mt-1 text-muted-foreground">
						Im Repo-Root <code class="rounded bg-muted px-1 py-0.5">pnpm audit:map</code> ausführen.
					</p>
				</div>
			</div>
		{:else}
			<div class="flex-1 overflow-hidden rounded-md border bg-background">
				<iframe
					src="/admin/complexity-map.html"
					title="Complexity Map"
					class="h-full w-full border-0"
					onerror={onError}
				></iframe>
			</div>
		{/if}
	</div>
{/if}
