import type { Quote } from './types';

/**
 * German inspirational quotes collection with multilingual support
 */
export const QUOTES: Quote[] = [
	// ============================================
	// MOTIVATION
	// ============================================
	{
		id: 'mot-1',
		text: {
			original: 'The only way to do great work is to love what you do.',
			de: 'Der einzige Weg, großartige Arbeit zu leisten, ist zu lieben, was man tut.',
			en: 'The only way to do great work is to love what you do.',
			it: "L'unico modo per fare un ottimo lavoro è amare quello che fai.",
			fr: "La seule façon de faire du bon travail est d'aimer ce que vous faites.",
			es: 'La única forma de hacer un gran trabajo es amar lo que haces.',
		},
		author: 'Steve Jobs',
		category: 'motivation',
		originalLanguage: 'en',
		source: 'Stanford Commencement Speech',
		year: 2005,
		tags: ['arbeit', 'leidenschaft', 'erfolg'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Unternehmer (1955-2011), Mitgründer von Apple Inc.',
			en: 'American entrepreneur (1955-2011), co-founder of Apple Inc.',
		},
	},
	{
		id: 'mot-2',
		text: {
			original:
				'Success is not final, failure is not fatal: it is the courage to continue that counts.',
			de: 'Erfolg ist nicht endgültig, Misserfolg ist nicht fatal: Was zählt, ist der Mut weiterzumachen.',
			en: 'Success is not final, failure is not fatal: it is the courage to continue that counts.',
			it: 'Il successo non è definitivo, il fallimento non è fatale: ciò che conta è il coraggio di continuare.',
			fr: "Le succès n'est pas définitif, l'échec n'est pas fatal : c'est le courage de continuer qui compte.",
			es: 'El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el coraje de continuar.',
		},
		author: 'Winston Churchill',
		category: 'motivation',
		originalLanguage: 'en',
		source: 'Zugeschrieben',
		year: 1941,
		tags: ['erfolg', 'misserfolg', 'mut', 'durchhaltevermögen'],
		verified: true,
		authorBio: {
			de: 'Britischer Staatsmann (1874-1965), Premierminister während des Zweiten Weltkriegs.',
			en: 'British statesman (1874-1965), Prime Minister during World War II.',
		},
	},
	{
		id: 'mot-3',
		text: {
			original: 'The future belongs to those who believe in the beauty of their dreams.',
			de: 'Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben.',
			en: 'The future belongs to those who believe in the beauty of their dreams.',
			it: 'Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.',
			fr: "L'avenir appartient à ceux qui croient en la beauté de leurs rêves.",
			es: 'El futuro pertenece a quienes creen en la belleza de sus sueños.',
		},
		author: 'Eleanor Roosevelt',
		category: 'motivation',
		originalLanguage: 'en',
		year: 1961,
		tags: ['zukunft', 'träume', 'glaube'],
		verified: true,
		authorBio: {
			de: 'US-amerikanische Menschenrechtsaktivistin (1884-1962), First Lady der USA.',
			en: 'American human rights activist (1884-1962), First Lady of the United States.',
		},
	},
	{
		id: 'mot-4',
		text: {
			original: "It's never too late to be what you might have been.",
			de: 'Es ist nie zu spät, das zu werden, was man hätte sein können.',
			en: "It's never too late to be what you might have been.",
			it: 'Non è mai troppo tardi per essere ciò che avresti potuto essere.',
			fr: "Il n'est jamais trop tard pour être ce que vous auriez pu être.",
			es: 'Nunca es demasiado tarde para ser lo que podrías haber sido.',
		},
		author: 'George Eliot',
		category: 'motivation',
		originalLanguage: 'en',
		year: 1870,
		tags: ['veränderung', 'potenzial', 'neuanfang'],
		verified: true,
		authorBio: {
			de: 'Englische Schriftstellerin (1819-1880), bürgerlicher Name Mary Ann Evans.',
			en: 'English novelist (1819-1880), pen name of Mary Ann Evans.',
		},
	},
	{
		id: 'mot-5',
		text: {
			original: 'Give every day the chance to become the most beautiful day of your life.',
			de: 'Gib jedem Tag die Chance, der schönste deines Lebens zu werden.',
			en: 'Give every day the chance to become the most beautiful day of your life.',
			it: 'Dai a ogni giorno la possibilità di diventare il più bello della tua vita.',
			fr: 'Donne à chaque jour la chance de devenir le plus beau jour de ta vie.',
			es: 'Dale a cada día la oportunidad de convertirse en el más hermoso de tu vida.',
		},
		author: 'Mark Twain',
		category: 'motivation',
		originalLanguage: 'en',
		year: 1890,
		tags: ['tag', 'leben', 'optimismus'],
		verified: false,
		authorBio: {
			de: 'US-amerikanischer Schriftsteller (1835-1910), bekannt für Tom Sawyer und Huckleberry Finn.',
			en: 'American writer (1835-1910), known for Tom Sawyer and Huckleberry Finn.',
		},
	},
	{
		id: 'mot-6',
		text: {
			original: 'Ἀρχὴ ἥμισυ παντός.',
			de: 'Der Anfang ist die Hälfte des Ganzen.',
			en: 'The beginning is half of the whole.',
			it: "L'inizio è la metà del tutto.",
			fr: 'Le commencement est la moitié du tout.',
			es: 'El comienzo es la mitad del todo.',
		},
		author: 'Aristoteles',
		category: 'motivation',
		originalLanguage: 'el',
		source: 'Politik',
		year: -350,
		tags: ['anfang', 'handeln', 'philosophie'],
		verified: true,
		authorBio: {
			de: 'Griechischer Philosoph (384-322 v. Chr.), Universalgelehrter der Antike.',
			en: 'Ancient Greek philosopher (384-322 BC), polymath of antiquity.',
		},
	},
	{
		id: 'mot-7',
		text: {
			original: 'Do something today that your future self will thank you for.',
			de: 'Tue heute etwas, wofür dein zukünftiges Ich dir danken wird.',
			en: 'Do something today that your future self will thank you for.',
			it: 'Fai qualcosa oggi di cui il tuo futuro io ti ringrazierà.',
			fr: "Fais quelque chose aujourd'hui dont ton futur toi te remerciera.",
			es: 'Haz algo hoy por lo que tu yo futuro te lo agradecerá.',
		},
		author: 'Sean Patrick Flanery',
		category: 'motivation',
		originalLanguage: 'en',
		year: 2012,
		tags: ['zukunft', 'handeln', 'selbstverbesserung'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Schauspieler (*1965), bekannt aus The Boondock Saints.',
			en: 'American actor (*1965), known for The Boondock Saints.',
		},
	},
	{
		id: 'mot-8',
		text: {
			original: '种一棵树最好的时间是二十年前，其次是现在。',
			de: 'Der beste Zeitpunkt einen Baum zu pflanzen war vor 20 Jahren. Der zweitbeste ist jetzt.',
			en: 'The best time to plant a tree was 20 years ago. The second best time is now.',
			it: 'Il momento migliore per piantare un albero era 20 anni fa. Il secondo momento migliore è adesso.',
			fr: 'Le meilleur moment pour planter un arbre était il y a 20 ans. Le deuxième meilleur moment est maintenant.',
			es: 'El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.',
		},
		author: 'Chinesisches Sprichwort',
		category: 'motivation',
		originalLanguage: 'zh',
		tags: ['handeln', 'zeit', 'anfang'],
		verified: true,
	},

	// ============================================
	// WEISHEIT
	// ============================================
	{
		id: 'weis-1',
		text: {
			original: '道可道，非常道。',
			de: 'Der Weg, der sich aussprechen lässt, ist nicht der ewige Weg.',
			en: 'The way that can be spoken of is not the eternal way.',
			it: 'La via che può essere espressa non è la via eterna.',
			fr: "La voie qui peut être exprimée par la parole n'est pas la Voie éternelle.",
			es: 'El camino que puede expresarse no es el camino eterno.',
		},
		author: 'Laozi',
		category: 'weisheit',
		originalLanguage: 'zh',
		source: 'Tao Te King, Kapitel 1',
		year: -600,
		tags: ['weg', 'tao', 'philosophie'],
		verified: true,
		authorBio: {
			de: 'Chinesischer Philosoph (6. Jh. v. Chr.), Begründer des Taoismus.',
			en: 'Chinese philosopher (6th century BC), founder of Taoism.',
		},
	},
	{
		id: 'weis-2',
		text: {
			original: 'Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.',
			de: 'Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.',
			en: 'He who fights may lose. He who does not fight has already lost.',
			it: 'Chi lotta può perdere. Chi non lotta ha già perso.',
			fr: 'Qui se bat peut perdre. Qui ne se bat pas a déjà perdu.',
			es: 'Quien lucha puede perder. Quien no lucha ya ha perdido.',
		},
		author: 'Bertolt Brecht',
		category: 'weisheit',
		originalLanguage: 'de',
		source: 'Die Mutter',
		year: 1932,
		tags: ['kampf', 'mut', 'handeln'],
		verified: true,
		authorBio: {
			de: 'Deutscher Dramatiker und Lyriker (1898-1956), Begründer des epischen Theaters.',
			en: 'German playwright and poet (1898-1956), founder of epic theatre.',
		},
	},
	{
		id: 'weis-3',
		text: {
			original: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.",
			de: 'Man sieht nur mit dem Herzen gut. Das Wesentliche ist für die Augen unsichtbar.',
			en: 'One sees clearly only with the heart. The essential is invisible to the eyes.',
			it: "Si vede bene solo con il cuore. L'essenziale è invisibile agli occhi.",
			fr: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.",
			es: 'Solo se ve bien con el corazón. Lo esencial es invisible a los ojos.',
		},
		author: 'Antoine de Saint-Exupéry',
		category: 'weisheit',
		originalLanguage: 'fr',
		source: 'Der kleine Prinz (Le Petit Prince)',
		year: 1943,
		tags: ['herz', 'sehen', 'wesentlich'],
		verified: true,
		authorBio: {
			de: 'Französischer Schriftsteller und Pilot (1900-1944), Autor von "Der kleine Prinz".',
			en: 'French writer and aviator (1900-1944), author of "The Little Prince".',
		},
	},
	{
		id: 'weis-4',
		text: {
			original: 'Non quia difficilia sunt non audemus, sed quia non audemus difficilia sunt.',
			de: 'Nicht weil es schwer ist, wagen wir es nicht, sondern weil wir es nicht wagen, ist es schwer.',
			en: 'It is not because things are difficult that we do not dare, but because we do not dare that things are difficult.',
			it: 'Non è perché le cose sono difficili che non osiamo, ma perché non osiamo che sono difficili.',
			fr: "Ce n'est pas parce que les choses sont difficiles que nous n'osons pas, c'est parce que nous n'osons pas qu'elles sont difficiles.",
			es: 'No es porque las cosas sean difíciles que no nos atrevemos, sino porque no nos atrevemos que son difíciles.',
		},
		author: 'Seneca',
		category: 'weisheit',
		originalLanguage: 'la',
		source: 'Epistulae morales ad Lucilium, Brief 104',
		year: 65,
		tags: ['mut', 'wagnis', 'schwierigkeit'],
		verified: true,
		authorBio: {
			de: 'Römischer Philosoph und Staatsmann (ca. 4 v. Chr. - 65 n. Chr.).',
			en: 'Roman philosopher and statesman (c. 4 BC - 65 AD).',
		},
	},
	{
		id: 'weis-5',
		text: {
			original: 'Scientia potentia est.',
			de: 'Wissen ist Macht.',
			en: 'Knowledge is power.',
			it: 'La conoscenza è potere.',
			fr: 'Le savoir est le pouvoir.',
			es: 'El conocimiento es poder.',
		},
		author: 'Francis Bacon',
		category: 'weisheit',
		originalLanguage: 'la',
		source: 'Meditationes Sacrae',
		year: 1597,
		tags: ['wissen', 'macht', 'bildung'],
		verified: true,
		authorBio: {
			de: 'Englischer Philosoph und Staatsmann (1561-1626), Begründer des Empirismus.',
			en: 'English philosopher and statesman (1561-1626), founder of empiricism.',
		},
	},
	{
		id: 'weis-6',
		text: {
			original: 'ἓν οἶδα ὅτι οὐδὲν οἶδα.',
			de: 'Ich weiß, dass ich nichts weiß.',
			en: 'I know that I know nothing.',
			it: 'So di non sapere.',
			fr: 'Je sais que je ne sais rien.',
			es: 'Solo sé que no sé nada.',
		},
		author: 'Sokrates',
		category: 'weisheit',
		originalLanguage: 'el',
		source: 'Überliefert durch Platon, Apologie des Sokrates',
		year: -399,
		tags: ['wissen', 'demut', 'philosophie'],
		verified: true,
		authorBio: {
			de: 'Griechischer Philosoph (469-399 v. Chr.), Begründer der abendländischen Philosophie.',
			en: 'Greek philosopher (469-399 BC), founder of Western philosophy.',
		},
	},
	{
		id: 'weis-7',
		text: {
			original: 'τὰ πάντα ῥεῖ.',
			de: 'Alles fließt.',
			en: 'Everything flows.',
			it: 'Tutto scorre.',
			fr: 'Tout coule.',
			es: 'Todo fluye.',
		},
		author: 'Heraklit',
		category: 'weisheit',
		originalLanguage: 'el',
		source: 'Fragmente',
		year: -500,
		tags: ['veränderung', 'leben', 'philosophie'],
		verified: true,
		authorBio: {
			de: 'Griechischer Philosoph aus Ephesos (ca. 535-475 v. Chr.).',
			en: 'Greek philosopher from Ephesus (c. 535-475 BC).',
		},
	},
	{
		id: 'weis-8',
		text: {
			original:
				'Handle nur nach derjenigen Maxime, durch die du zugleich wollen kannst, dass sie ein allgemeines Gesetz werde.',
			de: 'Handle nur nach derjenigen Maxime, durch die du zugleich wollen kannst, dass sie ein allgemeines Gesetz werde.',
			en: 'Act only according to that maxim by which you can at the same time will that it should become a universal law.',
			it: 'Agisci solo secondo quella massima che puoi al contempo volere che diventi una legge universale.',
			fr: "Agis seulement selon la maxime grâce à laquelle tu peux vouloir en même temps qu'elle devienne une loi universelle.",
			es: 'Obra solo según aquella máxima por la cual puedas querer que al mismo tiempo se convierta en ley universal.',
		},
		author: 'Immanuel Kant',
		category: 'weisheit',
		originalLanguage: 'de',
		source: 'Grundlegung zur Metaphysik der Sitten',
		year: 1785,
		tags: ['ethik', 'moral', 'philosophie', 'kategorischer imperativ'],
		verified: true,
		authorBio: {
			de: 'Deutscher Philosoph der Aufklärung (1724-1804).',
			en: 'German philosopher of the Enlightenment (1724-1804).',
		},
	},
	{
		id: 'weis-9',
		text: {
			original: '己所不欲，勿施於人。',
			de: 'Was du nicht willst, dass man dir tu, das füg auch keinem anderen zu.',
			en: 'Do not do to others what you do not want done to yourself.',
			it: 'Non fare agli altri ciò che non vorresti fosse fatto a te.',
			fr: "Ne fais pas aux autres ce que tu ne voudrais pas qu'on te fasse.",
			es: 'No hagas a otros lo que no quieras que te hagan a ti.',
		},
		author: 'Konfuzius',
		category: 'weisheit',
		originalLanguage: 'zh',
		source: 'Analekten (Lunyu), Kapitel 15',
		year: -500,
		tags: ['ethik', 'goldene regel', 'philosophie'],
		verified: true,
		authorBio: {
			de: 'Chinesischer Philosoph (551-479 v. Chr.), Begründer des Konfuzianismus.',
			en: 'Chinese philosopher (551-479 BC), founder of Confucianism.',
		},
	},

	// ============================================
	// LIEBE
	// ============================================
	{
		id: 'liebe-1',
		text: {
			original: 'Where there is love there is life.',
			de: 'Wo Liebe ist, da ist auch Leben.',
			en: 'Where there is love there is life.',
			it: "Dove c'è amore c'è vita.",
			fr: "Là où il y a de l'amour, il y a de la vie.",
			es: 'Donde hay amor hay vida.',
		},
		author: 'Mahatma Gandhi',
		category: 'liebe',
		originalLanguage: 'en',
		year: 1925,
		tags: ['liebe', 'leben'],
		verified: true,
		authorBio: {
			de: 'Indischer Unabhängigkeitskämpfer und geistiger Führer (1869-1948).',
			en: 'Indian independence activist and spiritual leader (1869-1948).',
		},
	},
	{
		id: 'liebe-2',
		text: {
			original:
				'Die Liebe allein versteht das Geheimnis, andere zu beschenken und dabei selbst reich zu werden.',
			de: 'Die Liebe allein versteht das Geheimnis, andere zu beschenken und dabei selbst reich zu werden.',
			en: 'Love alone understands the secret of giving to others and becoming rich oneself.',
			it: "Solo l'amore comprende il segreto di donare agli altri e arricchirsi.",
			fr: "Seul l'amour comprend le secret d'offrir aux autres et de s'enrichir soi-même.",
			es: 'Solo el amor entiende el secreto de dar a los demás y enriquecerse uno mismo.',
		},
		author: 'Clemens Brentano',
		category: 'liebe',
		originalLanguage: 'de',
		year: 1810,
		tags: ['liebe', 'geben', 'reichtum'],
		verified: true,
		authorBio: {
			de: 'Deutscher Dichter der Romantik (1778-1842).',
			en: 'German poet of the Romantic era (1778-1842).',
		},
	},
	{
		id: 'liebe-3',
		text: {
			original: "Il n'y a qu'un bonheur dans la vie, c'est d'aimer et d'être aimé.",
			de: 'Es gibt nur ein Glück in diesem Leben: zu lieben und geliebt zu werden.',
			en: 'There is only one happiness in this life: to love and be loved.',
			it: "C'è solo una felicità nella vita: amare ed essere amati.",
			fr: "Il n'y a qu'un bonheur dans la vie, c'est d'aimer et d'être aimé.",
			es: 'Solo hay una felicidad en la vida: amar y ser amado.',
		},
		author: 'George Sand',
		category: 'liebe',
		originalLanguage: 'fr',
		source: 'Brief an Lina Calamatta',
		year: 1862,
		tags: ['liebe', 'glück'],
		verified: true,
		authorBio: {
			de: 'Französische Schriftstellerin der Romantik (1804-1876), bürgerlicher Name Amantine Aurore Dupin.',
			en: 'French Romantic era novelist (1804-1876), born Amantine Aurore Dupin.',
		},
	},
	{
		id: 'liebe-4',
		text: {
			original: 'Liebe ist das einzige, was wächst, wenn wir es verschwenden.',
			de: 'Liebe ist das einzige, was wächst, wenn wir es verschwenden.',
			en: 'Love is the only thing that grows when we waste it.',
			it: "L'amore è l'unica cosa che cresce quando la sprechiamo.",
			fr: "L'amour est la seule chose qui grandit quand on la gaspille.",
			es: 'El amor es lo único que crece cuando lo derrochamos.',
		},
		author: 'Ricarda Huch',
		category: 'liebe',
		originalLanguage: 'de',
		year: 1920,
		tags: ['liebe', 'wachstum'],
		verified: true,
		authorBio: {
			de: 'Deutsche Dichterin, Philosophin und Historikerin (1864-1947).',
			en: 'German poet, philosopher, and historian (1864-1947).',
		},
	},
	{
		id: 'liebe-5',
		text: {
			original: "La plus grande chose du monde, c'est de savoir être à soi.",
			de: 'Die größte Sache der Welt ist es, zu wissen, wie man sich selbst gehört.',
			en: 'The greatest thing in the world is to know how to belong to oneself.',
			it: 'La cosa più grande del mondo è sapere come appartenere a se stessi.',
			fr: "La plus grande chose du monde, c'est de savoir être à soi.",
			es: 'La cosa más grande del mundo es saber cómo pertenecerse a uno mismo.',
		},
		author: 'Michel de Montaigne',
		category: 'liebe',
		originalLanguage: 'fr',
		source: 'Essais, Buch I, Kapitel 39',
		year: 1580,
		tags: ['selbstliebe', 'identität'],
		verified: true,
		authorBio: {
			de: 'Französischer Philosoph und Begründer der Essayistik (1533-1592).',
			en: 'French philosopher and founder of the essay form (1533-1592).',
		},
	},
	{
		id: 'liebe-6',
		text: {
			original: "Amare non è guardarsi l'un l'altro, ma guardare insieme nella stessa direzione.",
			de: 'Lieben, das heißt nicht, einander anschauen, sondern gemeinsam in die gleiche Richtung blicken.',
			en: 'Love does not consist in gazing at each other, but in looking outward together in the same direction.',
			it: "Amare non è guardarsi l'un l'altro, ma guardare insieme nella stessa direzione.",
			fr: "Aimer, ce n'est pas se regarder l'un l'autre, c'est regarder ensemble dans la même direction.",
			es: 'Amar no es mirarse el uno al otro, sino mirar juntos en la misma dirección.',
		},
		author: 'Antoine de Saint-Exupéry',
		category: 'liebe',
		originalLanguage: 'fr',
		source: 'Terre des hommes',
		year: 1939,
		tags: ['liebe', 'partnerschaft', 'gemeinsam'],
		verified: true,
		authorBio: {
			de: 'Französischer Schriftsteller und Pilot (1900-1944).',
			en: 'French writer and aviator (1900-1944).',
		},
	},

	// ============================================
	// LEBEN
	// ============================================
	{
		id: 'leben-1',
		text: {
			original: 'Life is like riding a bicycle. To keep your balance, you must keep moving.',
			de: 'Das Leben ist wie Fahrrad fahren. Um die Balance zu halten, musst du in Bewegung bleiben.',
			en: 'Life is like riding a bicycle. To keep your balance, you must keep moving.',
			it: "La vita è come andare in bicicletta. Per mantenere l'equilibrio devi muoverti.",
			fr: "La vie, c'est comme une bicyclette. Il faut avancer pour ne pas perdre l'équilibre.",
			es: 'La vida es como andar en bicicleta. Para mantener el equilibrio, debes seguir moviéndote.',
		},
		author: 'Albert Einstein',
		category: 'leben',
		originalLanguage: 'en',
		source: 'Brief an seinen Sohn Eduard',
		year: 1930,
		tags: ['leben', 'balance', 'bewegung'],
		verified: true,
		authorBio: {
			de: 'Deutsch-amerikanischer Physiker (1879-1955), Nobelpreisträger.',
			en: 'German-American physicist (1879-1955), Nobel laureate.',
		},
	},
	{
		id: 'leben-2',
		text: {
			original: "Life is what happens when you're busy making other plans.",
			de: 'Leben ist das, was passiert, während du damit beschäftigt bist, andere Pläne zu machen.',
			en: "Life is what happens when you're busy making other plans.",
			it: 'La vita è quello che ti succede mentre sei impegnato a fare altri progetti.',
			fr: "La vie est ce qui arrive pendant que vous êtes occupé à faire d'autres projets.",
			es: 'La vida es lo que pasa mientras estás ocupado haciendo otros planes.',
		},
		author: 'John Lennon',
		category: 'leben',
		originalLanguage: 'en',
		source: 'Beautiful Boy (Darling Boy)',
		year: 1980,
		tags: ['leben', 'pläne', 'gegenwart'],
		verified: true,
		authorBio: {
			de: 'Britischer Musiker (1940-1980), Mitbegründer der Beatles.',
			en: 'British musician (1940-1980), co-founder of the Beatles.',
		},
	},
	{
		id: 'leben-3',
		text: {
			original: 'Das Leben ist zu kurz für später.',
			de: 'Das Leben ist zu kurz für später.',
			en: 'Life is too short for later.',
			it: 'La vita è troppo breve per il dopo.',
			fr: 'La vie est trop courte pour plus tard.',
			es: 'La vida es demasiado corta para después.',
		},
		author: 'Alexandra Reinwarth',
		category: 'leben',
		originalLanguage: 'de',
		source: 'Buchtitel',
		year: 2017,
		tags: ['leben', 'zeit', 'gegenwart'],
		verified: true,
		authorBio: {
			de: 'Deutsche Autorin und Journalistin (*1972).',
			en: 'German author and journalist (*1972).',
		},
	},
	{
		id: 'leben-4',
		text: {
			original: 'Ὡς ἐσχάτην ἑκάστην ἡμέραν βίου διεξάγειν.',
			de: 'Lebe jeden Tag, als wäre es dein letzter.',
			en: 'Live every day as if it were your last.',
			it: "Vivi ogni giorno come se fosse l'ultimo.",
			fr: "Vis chaque jour comme si c'était le dernier.",
			es: 'Vive cada día como si fuera el último.',
		},
		author: 'Marcus Aurelius',
		category: 'leben',
		originalLanguage: 'el',
		source: 'Selbstbetrachtungen (Τὰ εἰς ἑαυτόν), Buch VII',
		year: 175,
		tags: ['leben', 'tag', 'gegenwart', 'stoizismus'],
		verified: true,
		authorBio: {
			de: 'Römischer Kaiser (121-180 n. Chr.) und stoischer Philosoph.',
			en: 'Roman Emperor (121-180 AD) and Stoic philosopher.',
		},
	},
	{
		id: 'leben-5',
		text: {
			original: 'Livet er ikke et problem, der skal løses, men en virkelighed, der skal opleves.',
			de: 'Das Leben ist kein Problem, das gelöst werden muss, sondern eine Wirklichkeit, die erfahren werden will.',
			en: 'Life is not a problem to be solved, but a reality to be experienced.',
			it: 'La vita non è un problema da risolvere, ma una realtà da vivere.',
			fr: "La vie n'est pas un problème à résoudre, mais une réalité à vivre.",
			es: 'La vida no es un problema a resolver, sino una realidad a experimentar.',
		},
		author: 'Søren Kierkegaard',
		category: 'leben',
		originalLanguage: 'da',
		year: 1843,
		tags: ['leben', 'erfahrung', 'philosophie', 'existenzialismus'],
		verified: true,
		authorBio: {
			de: 'Dänischer Philosoph (1813-1855), Begründer des Existentialismus.',
			en: 'Danish philosopher (1813-1855), founder of existentialism.',
		},
	},
	{
		id: 'leben-6',
		text: {
			original:
				'Wer sein Leben so einrichtet, dass er niemals auf die Nase fallen kann, der kann nur auf dem Bauch kriechen.',
			de: 'Wer sein Leben so einrichtet, dass er niemals auf die Nase fallen kann, der kann nur auf dem Bauch kriechen.',
			en: 'He who arranges his life so that he can never fall on his face can only crawl on his belly.',
			it: 'Chi organizza la sua vita in modo da non cadere mai sul naso può solo strisciare sulla pancia.',
			fr: 'Celui qui organise sa vie de façon à ne jamais tomber sur le nez ne peut que ramper sur le ventre.',
			es: 'Quien organiza su vida para nunca caer de cara solo puede arrastrarse sobre el vientre.',
		},
		author: 'Heinz Riesenhuber',
		category: 'leben',
		originalLanguage: 'de',
		year: 1990,
		tags: ['leben', 'risiko', 'mut'],
		verified: true,
		authorBio: {
			de: 'Deutscher Politiker (CDU, *1935), ehemaliger Bundesminister für Forschung.',
			en: 'German politician (CDU, *1935), former Federal Minister of Research.',
		},
	},
	{
		id: 'leben-7',
		text: {
			original: 'Carpe diem, quam minimum credula postero.',
			de: 'Genieße den Tag und vertraue möglichst wenig auf den folgenden.',
			en: 'Seize the day, putting as little trust as possible in the future.',
			it: 'Cogli il giorno, confidando il meno possibile nel domani.',
			fr: 'Cueille le jour présent sans te soucier du lendemain.',
			es: 'Aprovecha el día, confiando lo menos posible en el mañana.',
		},
		author: 'Horaz',
		category: 'leben',
		originalLanguage: 'la',
		source: 'Oden, Buch I, Ode 11',
		year: -23,
		tags: ['leben', 'gegenwart', 'carpe diem'],
		verified: true,
		authorBio: {
			de: 'Römischer Dichter (65-8 v. Chr.).',
			en: 'Roman poet (65-8 BC).',
		},
	},

	// ============================================
	// ERFOLG
	// ============================================
	{
		id: 'erfolg-1',
		text: {
			original:
				'Coming together is a beginning, staying together is progress, and working together is success.',
			de: 'Zusammenkommen ist ein Beginn, Zusammenbleiben ist ein Fortschritt, Zusammenarbeiten ist ein Erfolg.',
			en: 'Coming together is a beginning, staying together is progress, and working together is success.',
			it: 'Riunirsi è un inizio, restare insieme è un progresso, lavorare insieme è un successo.',
			fr: 'Se réunir est un début, rester ensemble est un progrès, travailler ensemble est un succès.',
			es: 'Reunirse es un comienzo, mantenerse juntos es un progreso, trabajar juntos es un éxito.',
		},
		author: 'Henry Ford',
		category: 'erfolg',
		originalLanguage: 'en',
		year: 1920,
		tags: ['erfolg', 'teamwork', 'zusammenarbeit'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Industrieller (1863-1947), Gründer der Ford Motor Company.',
			en: 'American industrialist (1863-1947), founder of Ford Motor Company.',
		},
	},
	{
		id: 'erfolg-2',
		text: {
			original:
				'The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.',
			de: 'Der Preis des Erfolges ist Hingabe, harte Arbeit und unablässiger Einsatz für das, was man erreichen will.',
			en: 'The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves.',
			it: 'Il prezzo del successo è il duro lavoro, la dedizione al compito da svolgere e la determinazione.',
			fr: 'Le prix du succès est le travail acharné, le dévouement au travail à accomplir et la détermination.',
			es: 'El precio del éxito es el trabajo duro, la dedicación a la tarea en cuestión y la determinación.',
		},
		author: 'Vince Lombardi',
		category: 'erfolg',
		originalLanguage: 'en',
		year: 1960,
		tags: ['erfolg', 'arbeit', 'hingabe'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Football-Trainer (1913-1970), Legende der NFL.',
			en: 'American football coach (1913-1970), NFL legend.',
		},
	},
	{
		id: 'erfolg-3',
		text: {
			original: "I have not failed. I've just found 10,000 ways that won't work.",
			de: 'Ich habe nicht versagt. Ich habe nur 10.000 Wege gefunden, die nicht funktionieren.',
			en: "I have not failed. I've just found 10,000 ways that won't work.",
			it: 'Non ho fallito. Ho solo trovato 10.000 modi che non funzionano.',
			fr: "Je n'ai pas échoué. J'ai juste trouvé 10 000 façons qui ne fonctionnent pas.",
			es: 'No he fracasado. Solo he encontrado 10.000 formas que no funcionan.',
		},
		author: 'Thomas Edison',
		category: 'erfolg',
		originalLanguage: 'en',
		year: 1878,
		tags: ['erfolg', 'scheitern', 'ausdauer', 'innovation'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Erfinder und Unternehmer (1847-1931).',
			en: 'American inventor and businessman (1847-1931).',
		},
	},
	{
		id: 'erfolg-4',
		text: {
			original: 'Erfolg hat drei Buchstaben: TUN.',
			de: 'Erfolg hat drei Buchstaben: TUN.',
			en: 'Success has three letters: DO.',
			it: 'Il successo ha tre lettere: FARE.',
			fr: 'Le succès a trois lettres : AGIR.',
			es: 'El éxito tiene tres letras: HAZ.',
		},
		author: 'Johann Wolfgang von Goethe',
		category: 'erfolg',
		originalLanguage: 'de',
		year: 1810,
		tags: ['erfolg', 'handeln'],
		verified: false,
		authorBio: {
			de: 'Deutscher Dichter und Naturforscher (1749-1832).',
			en: 'German poet and naturalist (1749-1832).',
		},
	},
	{
		id: 'erfolg-5',
		text: {
			original:
				'Es ist nicht genug, zu wissen, man muss auch anwenden; es ist nicht genug, zu wollen, man muss auch tun.',
			de: 'Es ist nicht genug, zu wissen, man muss auch anwenden; es ist nicht genug, zu wollen, man muss auch tun.',
			en: 'It is not enough to know, one must also apply; it is not enough to want, one must also do.',
			it: 'Non basta sapere, bisogna anche applicare; non basta volere, bisogna anche fare.',
			fr: 'Il ne suffit pas de savoir, il faut aussi appliquer ; il ne suffit pas de vouloir, il faut aussi agir.',
			es: 'No basta saber, se debe también aplicar; no basta querer, se debe también hacer.',
		},
		author: 'Johann Wolfgang von Goethe',
		category: 'erfolg',
		originalLanguage: 'de',
		source: 'Wilhelm Meisters Wanderjahre',
		year: 1821,
		tags: ['erfolg', 'handeln', 'wissen'],
		verified: true,
		authorBio: {
			de: 'Deutscher Dichter und Naturforscher (1749-1832).',
			en: 'German poet and naturalist (1749-1832).',
		},
	},
	{
		id: 'erfolg-6',
		text: {
			original: 'The only place where success comes before work is in the dictionary.',
			de: 'Der einzige Ort, an dem Erfolg vor der Arbeit kommt, ist im Wörterbuch.',
			en: 'The only place where success comes before work is in the dictionary.',
			it: "L'unico posto dove il successo viene prima del lavoro è nel dizionario.",
			fr: 'Le seul endroit où le succès vient avant le travail est dans le dictionnaire.',
			es: 'El único lugar donde el éxito viene antes que el trabajo es en el diccionario.',
		},
		author: 'Vidal Sassoon',
		category: 'erfolg',
		originalLanguage: 'en',
		year: 1970,
		tags: ['erfolg', 'arbeit'],
		verified: true,
		authorBio: {
			de: 'Britischer Friseur und Unternehmer (1928-2012).',
			en: 'British hairdresser and businessman (1928-2012).',
		},
	},

	// ============================================
	// GLÜCK
	// ============================================
	{
		id: 'glueck-1',
		text: {
			original: 'Das Glück ist das einzige, das sich verdoppelt, wenn man es teilt.',
			de: 'Glück ist das Einzige, das sich verdoppelt, wenn man es teilt.',
			en: 'Happiness is the only thing that doubles when you share it.',
			it: "La felicità è l'unica cosa che raddoppia quando la condividi.",
			fr: 'Le bonheur est la seule chose qui double quand on le partage.',
			es: 'La felicidad es lo único que se duplica cuando se comparte.',
		},
		author: 'Albert Schweitzer',
		category: 'glueck',
		originalLanguage: 'de',
		year: 1950,
		tags: ['glück', 'teilen'],
		verified: true,
		authorBio: {
			de: 'Deutsch-französischer Arzt, Theologe und Friedensnobelpreisträger (1875-1965).',
			en: 'German-French physician, theologian, and Nobel Peace Prize laureate (1875-1965).',
		},
	},
	{
		id: 'glueck-2',
		text: {
			original: 'सुखं न लभ्यते सुखेन।',
			de: 'Es gibt keinen Weg zum Glück. Glücklich sein ist der Weg.',
			en: 'There is no path to happiness. Happiness is the path.',
			it: 'Non esiste un percorso verso la felicità. La felicità è il percorso.',
			fr: "Il n'y a pas de chemin vers le bonheur. Le bonheur est le chemin.",
			es: 'No hay un camino hacia la felicidad. La felicidad es el camino.',
		},
		author: 'Buddha',
		category: 'glueck',
		originalLanguage: 'sa',
		year: -500,
		tags: ['glück', 'weg', 'leben', 'buddhismus'],
		verified: true,
		authorBio: {
			de: 'Begründer des Buddhismus (ca. 563-483 v. Chr.).',
			en: 'Founder of Buddhism (c. 563-483 BC).',
		},
	},
	{
		id: 'glueck-3',
		text: {
			original: 'It is not happy people who are thankful. It is thankful people who are happy.',
			de: 'Nicht die Glücklichen sind dankbar. Es sind die Dankbaren, die glücklich sind.',
			en: 'It is not happy people who are thankful. It is thankful people who are happy.',
			it: 'Non sono le persone felici ad essere grate. Sono le persone grate ad essere felici.',
			fr: 'Ce ne sont pas les gens heureux qui sont reconnaissants. Ce sont les gens reconnaissants qui sont heureux.',
			es: 'No son las personas felices las que son agradecidas. Son las personas agradecidas las que son felices.',
		},
		author: 'Francis Bacon',
		category: 'glueck',
		originalLanguage: 'en',
		year: 1600,
		tags: ['glück', 'dankbarkeit'],
		verified: false,
		authorBio: {
			de: 'Englischer Philosoph und Staatsmann (1561-1626).',
			en: 'English philosopher and statesman (1561-1626).',
		},
	},
	{
		id: 'glueck-4',
		text: {
			original: 'Sammenligning er enden på lykke og begyndelsen på utilfredshed.',
			de: 'Das Vergleichen ist das Ende des Glücks und der Anfang der Unzufriedenheit.',
			en: 'Comparison is the end of happiness and the beginning of discontent.',
			it: "Il confronto è la fine della felicità e l'inizio dell'insoddisfazione.",
			fr: "La comparaison est la fin du bonheur et le début de l'insatisfaction.",
			es: 'La comparación es el fin de la felicidad y el comienzo de la insatisfacción.',
		},
		author: 'Søren Kierkegaard',
		category: 'glueck',
		originalLanguage: 'da',
		year: 1847,
		tags: ['glück', 'vergleich', 'zufriedenheit'],
		verified: true,
		authorBio: {
			de: 'Dänischer Philosoph (1813-1855).',
			en: 'Danish philosopher (1813-1855).',
		},
	},
	{
		id: 'glueck-5',
		text: {
			original:
				'Glück entsteht oft durch Aufmerksamkeit in kleinen Dingen, Unglück oft durch Vernachlässigung kleiner Dinge.',
			de: 'Glück entsteht oft durch Aufmerksamkeit in kleinen Dingen, Unglück oft durch Vernachlässigung kleiner Dinge.',
			en: 'Happiness often comes from attention to small things, unhappiness often from neglecting small things.',
			it: "La felicità nasce spesso dall'attenzione alle piccole cose, l'infelicità spesso dalla trascuratezza delle piccole cose.",
			fr: "Le bonheur vient souvent de l'attention aux petites choses, le malheur souvent de la négligence des petites choses.",
			es: 'La felicidad a menudo proviene de la atención a las pequeñas cosas, la infelicidad a menudo del descuido de las pequeñas cosas.',
		},
		author: 'Wilhelm Busch',
		category: 'glueck',
		originalLanguage: 'de',
		year: 1875,
		tags: ['glück', 'aufmerksamkeit', 'details'],
		verified: true,
		authorBio: {
			de: 'Deutscher Dichter, Zeichner und Maler (1832-1908).',
			en: 'German poet, illustrator, and painter (1832-1908).',
		},
	},
	{
		id: 'glueck-6',
		text: {
			original: 'Εὐδαιμονία ἐστὶν ἐνέργεια ψυχῆς κατ᾽ ἀρετὴν τελείαν.',
			de: 'Glückseligkeit ist eine Tätigkeit der Seele gemäß vollkommener Tugend.',
			en: 'Happiness is an activity of the soul in accordance with complete virtue.',
			it: "La felicità è un'attività dell'anima in accordo con la virtù perfetta.",
			fr: "Le bonheur est une activité de l'âme conforme à la vertu parfaite.",
			es: 'La felicidad es una actividad del alma de acuerdo con la virtud perfecta.',
		},
		author: 'Aristoteles',
		category: 'glueck',
		originalLanguage: 'el',
		source: 'Nikomachische Ethik, Buch I',
		year: -340,
		tags: ['glück', 'tugend', 'seele', 'philosophie'],
		verified: true,
		authorBio: {
			de: 'Griechischer Philosoph (384-322 v. Chr.).',
			en: 'Greek philosopher (384-322 BC).',
		},
	},

	// ============================================
	// FREUNDSCHAFT
	// ============================================
	{
		id: 'freund-1',
		text: {
			original:
				'A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow.',
			de: 'Ein Freund ist jemand, der dich kennt wie du bist, versteht wo du warst, akzeptiert was aus dir geworden ist, und dir dennoch erlaubt zu wachsen.',
			en: 'A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow.',
			it: 'Un amico è qualcuno che ti conosce per quello che sei, capisce dove sei stato, accetta ciò che sei diventato, e ti permette ancora di crescere.',
			fr: "Un ami est quelqu'un qui te connaît tel que tu es, comprend où tu as été, accepte ce que tu es devenu, et te permet encore de grandir.",
			es: 'Un amigo es alguien que te conoce como eres, entiende dónde has estado, acepta en lo que te has convertido, y aún así te permite crecer.',
		},
		author: 'William Shakespeare',
		category: 'freundschaft',
		originalLanguage: 'en',
		year: 1600,
		tags: ['freundschaft', 'wachstum', 'akzeptanz'],
		verified: false,
		authorBio: {
			de: 'Englischer Dramatiker und Dichter (1564-1616).',
			en: 'English playwright and poet (1564-1616).',
		},
	},
	{
		id: 'freund-2',
		text: {
			original: 'Φιλία ψυχὴ δύο σώμασιν ἐνοικοῦσα.',
			de: 'Freundschaft ist eine Seele in zwei Körpern.',
			en: 'Friendship is one soul dwelling in two bodies.',
			it: "L'amicizia è un'anima che abita in due corpi.",
			fr: "L'amitié est une âme habitant deux corps.",
			es: 'La amistad es un alma que habita en dos cuerpos.',
		},
		author: 'Aristoteles',
		category: 'freundschaft',
		originalLanguage: 'el',
		source: 'Überliefert durch Diogenes Laertios',
		year: -340,
		tags: ['freundschaft', 'seele', 'verbindung'],
		verified: true,
		authorBio: {
			de: 'Griechischer Philosoph (384-322 v. Chr.).',
			en: 'Greek philosopher (384-322 BC).',
		},
	},
	{
		id: 'freund-3',
		text: {
			original: 'A friend is a person with whom I may be sincere. Before him I may think aloud.',
			de: 'Ein Freund ist ein Mensch, vor dem ich aufrichtig sein kann. Vor ihm kann ich laut denken.',
			en: 'A friend is a person with whom I may be sincere. Before him I may think aloud.',
			it: 'Un amico è una persona con cui posso essere sincero. Davanti a lui posso pensare ad alta voce.',
			fr: 'Un ami est une personne avec qui je peux être sincère. Devant lui, je peux penser tout haut.',
			es: 'Un amigo es una persona con quien puedo ser sincero. Ante él puedo pensar en voz alta.',
		},
		author: 'Ralph Waldo Emerson',
		category: 'freundschaft',
		originalLanguage: 'en',
		source: 'Essays: First Series - Friendship',
		year: 1841,
		tags: ['freundschaft', 'ehrlichkeit', 'vertrauen'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Philosoph und Schriftsteller (1803-1882).',
			en: 'American philosopher and writer (1803-1882).',
		},
	},
	{
		id: 'freund-4',
		text: {
			original: 'ἡ φιλία τῶν ἀναγκαιοτάτων εἰς τὸν βίον.',
			de: 'Die Freundschaft gehört zum Notwendigsten in unserem Leben.',
			en: 'Friendship is one of the most necessary things in life.',
			it: "L'amicizia è una delle cose più necessarie nella vita.",
			fr: "L'amitié est l'une des choses les plus nécessaires dans la vie.",
			es: 'La amistad es una de las cosas más necesarias en la vida.',
		},
		author: 'Aristoteles',
		category: 'freundschaft',
		originalLanguage: 'el',
		source: 'Nikomachische Ethik, Buch VIII',
		year: -340,
		tags: ['freundschaft', 'leben', 'notwendigkeit'],
		verified: true,
		authorBio: {
			de: 'Griechischer Philosoph (384-322 v. Chr.).',
			en: 'Greek philosopher (384-322 BC).',
		},
	},
	{
		id: 'freund-5',
		text: {
			original: 'Amicus certus in re incerta cernitur.',
			de: 'Den wahren Freund erkennt man in der Not.',
			en: 'A true friend is recognized in uncertain times.',
			it: 'Un vero amico si riconosce nei momenti difficili.',
			fr: "C'est dans l'adversité qu'on reconnaît ses vrais amis.",
			es: 'En la adversidad se conoce al verdadero amigo.',
		},
		author: 'Cicero',
		category: 'freundschaft',
		originalLanguage: 'la',
		source: 'De amicitia',
		year: -44,
		tags: ['freundschaft', 'not', 'treue'],
		verified: true,
		authorBio: {
			de: 'Römischer Staatsmann, Redner und Philosoph (106-43 v. Chr.).',
			en: 'Roman statesman, orator, and philosopher (106-43 BC).',
		},
	},

	// ============================================
	// MUT
	// ============================================
	{
		id: 'mut-1',
		text: {
			original: 'Θάρσος μὲν ἔργου ἀρχή, τύχη δὲ τέλους κυρία.',
			de: 'Mut steht am Anfang des Handelns, Glück am Ende.',
			en: 'Courage stands at the beginning of action, fortune at the end.',
			it: "Il coraggio sta all'inizio dell'azione, la fortuna alla fine.",
			fr: "Le courage est au début de l'action, la chance à la fin.",
			es: 'El coraje está al comienzo de la acción, la suerte al final.',
		},
		author: 'Demokrit',
		category: 'mut',
		originalLanguage: 'el',
		source: 'Fragmente',
		year: -400,
		tags: ['mut', 'handeln', 'glück'],
		verified: true,
		authorBio: {
			de: 'Griechischer Philosoph (ca. 460-370 v. Chr.), Begründer der Atomistik.',
			en: 'Greek philosopher (c. 460-370 BC), founder of atomism.',
		},
	},
	{
		id: 'mut-2',
		text: {
			original: 'Wer wagt, gewinnt.',
			de: 'Wer wagt, gewinnt.',
			en: 'Who dares, wins.',
			it: 'Chi osa, vince.',
			fr: 'Qui ose, gagne.',
			es: 'Quien se atreve, gana.',
		},
		author: 'Deutsches Sprichwort',
		category: 'mut',
		originalLanguage: 'de',
		tags: ['mut', 'wagnis', 'erfolg'],
		verified: true,
	},
	{
		id: 'mut-3',
		text: {
			original: 'Courage is resistance to fear, mastery of fear, not absence of fear.',
			de: 'Mut ist Widerstand gegen die Angst, Beherrschung der Angst – nicht Abwesenheit von Angst.',
			en: 'Courage is resistance to fear, mastery of fear, not absence of fear.',
			it: 'Il coraggio è resistenza alla paura, dominio della paura, non assenza di paura.',
			fr: "Le courage est la résistance à la peur, la maîtrise de la peur, pas l'absence de peur.",
			es: 'El coraje es resistencia al miedo, dominio del miedo, no ausencia de miedo.',
		},
		author: 'Mark Twain',
		category: 'mut',
		originalLanguage: 'en',
		source: "Pudd'nhead Wilson",
		year: 1894,
		tags: ['mut', 'angst', 'beherrschung'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Schriftsteller (1835-1910).',
			en: 'American writer (1835-1910).',
		},
	},
	{
		id: 'mut-4',
		text: {
			original:
				'Courage is not the absence of fear, but rather the judgment that something else is more important than fear.',
			de: 'Mut ist nicht die Abwesenheit von Angst, sondern die Erkenntnis, dass etwas anderes wichtiger ist als Angst.',
			en: 'Courage is not the absence of fear, but rather the judgment that something else is more important than fear.',
			it: "Il coraggio non è l'assenza di paura, ma piuttosto il giudizio che qualcos'altro è più importante della paura.",
			fr: "Le courage n'est pas l'absence de peur, mais plutôt le jugement que quelque chose d'autre est plus important que la peur.",
			es: 'El coraje no es la ausencia de miedo, sino más bien el juicio de que algo más es más importante que el miedo.',
		},
		author: 'Ambrose Redmoon',
		category: 'mut',
		originalLanguage: 'en',
		source: 'No Peaceful Warriors!',
		year: 1991,
		tags: ['mut', 'angst', 'prioritäten'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Schriftsteller und Rockband-Manager (1933-1996).',
			en: 'American writer and rock band manager (1933-1996).',
		},
	},
	{
		id: 'mut-5',
		text: {
			original: 'In the middle of difficulty lies opportunity.',
			de: 'Inmitten der Schwierigkeit liegt die Möglichkeit.',
			en: 'In the middle of difficulty lies opportunity.',
			it: "Nel mezzo della difficoltà giace l'opportunità.",
			fr: "Au milieu de la difficulté se trouve l'opportunité.",
			es: 'En medio de la dificultad yace la oportunidad.',
		},
		author: 'Albert Einstein',
		category: 'mut',
		originalLanguage: 'en',
		year: 1939,
		tags: ['mut', 'schwierigkeit', 'chance'],
		verified: true,
		authorBio: {
			de: 'Deutsch-amerikanischer Physiker (1879-1955).',
			en: 'German-American physicist (1879-1955).',
		},
	},
	{
		id: 'mut-6',
		text: {
			original: 'Audentes fortuna iuvat.',
			de: 'Das Glück begünstigt die Mutigen.',
			en: 'Fortune favors the bold.',
			it: 'La fortuna aiuta gli audaci.',
			fr: 'La fortune sourit aux audacieux.',
			es: 'La fortuna favorece a los audaces.',
		},
		author: 'Vergil',
		category: 'mut',
		originalLanguage: 'la',
		source: 'Aeneis, Buch X',
		year: -19,
		tags: ['mut', 'glück', 'wagnis'],
		verified: true,
		authorBio: {
			de: 'Römischer Dichter (70-19 v. Chr.).',
			en: 'Roman poet (70-19 BC).',
		},
	},

	// ============================================
	// HOFFNUNG
	// ============================================
	{
		id: 'hoff-1',
		text: {
			original: 'আশা একটি পাখি যা অন্ধকার রাতেও গান করে।',
			de: 'Hoffnung ist ein Vogel, der singt, wenn die Nacht noch dunkel ist.',
			en: 'Hope is a bird that sings when the night is still dark.',
			it: 'La speranza è un uccello che canta quando la notte è ancora buia.',
			fr: "L'espoir est un oiseau qui chante quand la nuit est encore sombre.",
			es: 'La esperanza es un pájaro que canta cuando la noche aún está oscura.',
		},
		author: 'Rabindranath Tagore',
		category: 'hoffnung',
		originalLanguage: 'bn',
		year: 1910,
		tags: ['hoffnung', 'dunkelheit', 'licht'],
		verified: true,
		authorBio: {
			de: 'Indischer Dichter (1861-1941), Nobelpreisträger für Literatur 1913.',
			en: 'Indian poet (1861-1941), Nobel laureate in Literature 1913.',
		},
	},
	{
		id: 'hoff-2',
		text: {
			original: 'Nach dem Regen scheint die Sonne.',
			de: 'Nach jedem Sturm scheint auch wieder die Sonne.',
			en: 'After every storm, the sun shines again.',
			it: 'Dopo ogni tempesta, il sole torna a splendere.',
			fr: 'Après chaque tempête, le soleil brille à nouveau.',
			es: 'Después de cada tormenta, el sol vuelve a brillar.',
		},
		author: 'Deutsches Sprichwort',
		category: 'hoffnung',
		originalLanguage: 'de',
		tags: ['hoffnung', 'sturm', 'sonne'],
		verified: true,
	},
	{
		id: 'hoff-3',
		text: {
			original: 'Auch aus Steinen, die einem in den Weg gelegt werden, kann man Schönes bauen.',
			de: 'Auch aus Steinen, die einem in den Weg gelegt werden, kann man Schönes bauen.',
			en: 'Even from the stones placed in your path, you can build something beautiful.',
			it: 'Anche dalle pietre che ti mettono sulla strada, puoi costruire qualcosa di bello.',
			fr: 'Même des pierres placées sur ton chemin, tu peux construire quelque chose de beau.',
			es: 'Incluso de las piedras que te ponen en el camino, puedes construir algo hermoso.',
		},
		author: 'Johann Wolfgang von Goethe',
		category: 'hoffnung',
		originalLanguage: 'de',
		year: 1810,
		tags: ['hoffnung', 'hindernisse', 'kreativität'],
		verified: true,
		authorBio: {
			de: 'Deutscher Dichter und Naturforscher (1749-1832).',
			en: 'German poet and naturalist (1749-1832).',
		},
	},
	{
		id: 'hoff-4',
		text: {
			original: 'Hope is being able to see that there is light despite all of the darkness.',
			de: 'Hoffnung bedeutet, das Licht zu sehen, obwohl alles dunkel ist.',
			en: 'Hope is being able to see that there is light despite all of the darkness.',
			it: "La speranza è essere in grado di vedere che c'è luce nonostante tutta l'oscurità.",
			fr: "L'espoir, c'est être capable de voir qu'il y a de la lumière malgré toute l'obscurité.",
			es: 'La esperanza es ser capaz de ver que hay luz a pesar de toda la oscuridad.',
		},
		author: 'Desmond Tutu',
		category: 'hoffnung',
		originalLanguage: 'en',
		year: 1984,
		tags: ['hoffnung', 'licht', 'dunkelheit'],
		verified: true,
		authorBio: {
			de: 'Südafrikanischer Erzbischof und Friedensnobelpreisträger (1931-2021).',
			en: 'South African archbishop and Nobel Peace Prize laureate (1931-2021).',
		},
	},
	{
		id: 'hoff-5',
		text: {
			original: 'Dum spiro, spero.',
			de: 'Solange ich atme, hoffe ich.',
			en: 'While I breathe, I hope.',
			it: 'Finché respiro, spero.',
			fr: "Tant que je respire, j'espère.",
			es: 'Mientras respiro, espero.',
		},
		author: 'Cicero',
		category: 'hoffnung',
		originalLanguage: 'la',
		source: 'Epistulae ad Atticum',
		year: -43,
		tags: ['hoffnung', 'leben', 'ausdauer'],
		verified: true,
		authorBio: {
			de: 'Römischer Staatsmann und Philosoph (106-43 v. Chr.).',
			en: 'Roman statesman and philosopher (106-43 BC).',
		},
	},

	// ============================================
	// NATUR
	// ============================================
	{
		id: 'natur-1',
		text: {
			original: 'Die Natur ist das einzige Buch, das auf allen Blättern großen Gehalt bietet.',
			de: 'Die Natur ist das einzige Buch, das auf allen Blättern großen Gehalt bietet.',
			en: 'Nature is the only book that offers great content on every page.',
			it: "La natura è l'unico libro che offre un grande contenuto in ogni pagina.",
			fr: 'La nature est le seul livre qui offre un grand contenu à chaque page.',
			es: 'La naturaleza es el único libro que ofrece un gran contenido en cada página.',
		},
		author: 'Johann Wolfgang von Goethe',
		category: 'natur',
		originalLanguage: 'de',
		year: 1820,
		tags: ['natur', 'buch', 'weisheit'],
		verified: true,
		authorBio: {
			de: 'Deutscher Dichter und Naturforscher (1749-1832).',
			en: 'German poet and naturalist (1749-1832).',
		},
	},
	{
		id: 'natur-2',
		text: {
			original: 'Look deep into nature, and then you will understand everything better.',
			de: 'Schau tief in die Natur, und dann wirst du alles besser verstehen.',
			en: 'Look deep into nature, and then you will understand everything better.',
			it: 'Guarda in profondità nella natura, e poi capirai tutto meglio.',
			fr: 'Regarde profondément dans la nature, et alors tu comprendras tout mieux.',
			es: 'Mira profundamente en la naturaleza, y entonces entenderás todo mejor.',
		},
		author: 'Albert Einstein',
		category: 'natur',
		originalLanguage: 'en',
		year: 1930,
		tags: ['natur', 'verstehen', 'weisheit'],
		verified: true,
		authorBio: {
			de: 'Deutsch-amerikanischer Physiker (1879-1955).',
			en: 'German-American physicist (1879-1955).',
		},
	},
	{
		id: 'natur-3',
		text: {
			original: 'Natura non facit saltus.',
			de: 'Die Natur macht keine Sprünge.',
			en: 'Nature does not make jumps.',
			it: 'La natura non fa salti.',
			fr: 'La nature ne fait pas de sauts.',
			es: 'La naturaleza no da saltos.',
		},
		author: 'Carl von Linné',
		category: 'natur',
		originalLanguage: 'la',
		source: 'Philosophia Botanica',
		year: 1751,
		tags: ['natur', 'evolution', 'kontinuität'],
		verified: true,
		authorBio: {
			de: 'Schwedischer Naturforscher (1707-1778), Begründer der modernen Taxonomie.',
			en: 'Swedish naturalist (1707-1778), founder of modern taxonomy.',
		},
	},
	{
		id: 'natur-4',
		text: {
			original:
				'Forget not that the earth delights to feel your bare feet and the winds long to play with your hair.',
			de: 'Vergiss nicht, dass die Erde sich freut, deine nackten Füße zu fühlen, und die Winde sich danach sehnen, mit deinem Haar zu spielen.',
			en: 'Forget not that the earth delights to feel your bare feet and the winds long to play with your hair.',
			it: 'Non dimenticare che la terra si rallegra di sentire i tuoi piedi nudi e i venti desiderano giocare con i tuoi capelli.',
			fr: "N'oublie pas que la terre se réjouit de sentir tes pieds nus et que les vents aspirent à jouer avec tes cheveux.",
			es: 'No olvides que la tierra se deleita en sentir tus pies descalzos y los vientos anhelan jugar con tu cabello.',
		},
		author: 'Khalil Gibran',
		category: 'natur',
		originalLanguage: 'en',
		source: 'The Prophet',
		year: 1923,
		tags: ['natur', 'freiheit', 'verbindung'],
		verified: true,
		authorBio: {
			de: 'Libanesisch-amerikanischer Dichter und Philosoph (1883-1931).',
			en: 'Lebanese-American poet and philosopher (1883-1931).',
		},
	},
	{
		id: 'natur-5',
		text: {
			original: 'In every walk with nature, one receives far more than he seeks.',
			de: 'Bei jedem Spaziergang mit der Natur erhält man weit mehr, als man sucht.',
			en: 'In every walk with nature, one receives far more than he seeks.',
			it: 'In ogni passeggiata con la natura, si riceve molto più di quanto si cerca.',
			fr: "Dans chaque promenade avec la nature, on reçoit bien plus que ce qu'on cherche.",
			es: 'En cada paseo con la naturaleza, uno recibe mucho más de lo que busca.',
		},
		author: 'John Muir',
		category: 'natur',
		originalLanguage: 'en',
		year: 1890,
		tags: ['natur', 'spaziergang', 'geschenk'],
		verified: true,
		authorBio: {
			de: 'Schottisch-amerikanischer Naturforscher und Umweltschützer (1838-1914).',
			en: 'Scottish-American naturalist and conservationist (1838-1914).',
		},
	},
	{
		id: 'natur-6',
		text: {
			original: 'Φύσις κρύπτεσθαι φιλεῖ.',
			de: 'Die Natur liebt es, sich zu verbergen.',
			en: 'Nature loves to hide.',
			it: 'La natura ama nascondersi.',
			fr: 'La nature aime se cacher.',
			es: 'La naturaleza ama ocultarse.',
		},
		author: 'Heraklit',
		category: 'natur',
		originalLanguage: 'el',
		source: 'Fragment 123',
		year: -500,
		tags: ['natur', 'geheimnis', 'philosophie'],
		verified: true,
		authorBio: {
			de: 'Griechischer Philosoph aus Ephesos (ca. 535-475 v. Chr.).',
			en: 'Greek philosopher from Ephesus (c. 535-475 BC).',
		},
	},

	// ============================================
	// HUMOR
	// ============================================
	{
		id: 'humor-1',
		text: {
			original: 'Be yourself; everyone else is already taken.',
			de: 'Sei du selbst; alle anderen sind bereits vergeben.',
			en: 'Be yourself; everyone else is already taken.',
			it: 'Sii te stesso; tutti gli altri sono già occupati.',
			fr: 'Sois toi-même ; tous les autres sont déjà pris.',
			es: 'Sé tú mismo; todos los demás ya están ocupados.',
		},
		author: 'Oscar Wilde',
		category: 'humor',
		originalLanguage: 'en',
		tags: ['humor', 'identität', 'selbst'],
		verified: true,
		authorBio: {
			de: 'Irischer Schriftsteller und Dramatiker (1854-1900).',
			en: 'Irish writer and playwright (1854-1900).',
		},
	},
	{
		id: 'humor-2',
		text: {
			original: "I have not failed. I've just found 10,000 ways that won't work.",
			de: 'Ich habe nicht versagt. Ich habe nur 10.000 Wege gefunden, die nicht funktionieren.',
			en: "I have not failed. I've just found 10,000 ways that won't work.",
			it: 'Non ho fallito. Ho solo trovato 10.000 modi che non funzionano.',
			fr: "Je n'ai pas échoué. J'ai juste trouvé 10 000 façons qui ne fonctionnent pas.",
			es: 'No he fracasado. Solo he encontrado 10.000 formas que no funcionan.',
		},
		author: 'Thomas Edison',
		category: 'humor',
		originalLanguage: 'en',
		tags: ['humor', 'ausdauer', 'erfindung'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Erfinder und Unternehmer (1847-1931).',
			en: 'American inventor and businessman (1847-1931).',
		},
	},
	{
		id: 'humor-3',
		text: {
			original: 'I can resist everything except temptation.',
			de: 'Ich kann allem widerstehen, nur nicht der Versuchung.',
			en: 'I can resist everything except temptation.',
			it: 'Posso resistere a tutto tranne che alla tentazione.',
			fr: 'Je peux résister à tout, sauf à la tentation.',
			es: 'Puedo resistir todo, excepto la tentación.',
		},
		author: 'Oscar Wilde',
		category: 'humor',
		originalLanguage: 'en',
		source: "Lady Windermere's Fan",
		year: 1892,
		tags: ['humor', 'versuchung', 'ironie'],
		verified: true,
	},
	{
		id: 'humor-4',
		text: {
			original:
				'Zwei Dinge sind unendlich, das Universum und die menschliche Dummheit, aber bei dem Universum bin ich mir noch nicht ganz sicher.',
			de: 'Zwei Dinge sind unendlich, das Universum und die menschliche Dummheit, aber bei dem Universum bin ich mir noch nicht ganz sicher.',
			en: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
			it: "Due cose sono infinite: l'universo e la stupidità umana; e non sono sicuro dell'universo.",
			fr: "Deux choses sont infinies : l'univers et la bêtise humaine ; et je ne suis pas sûr de l'univers.",
			es: 'Dos cosas son infinitas: el universo y la estupidez humana; y no estoy seguro del universo.',
		},
		author: 'Albert Einstein',
		category: 'humor',
		originalLanguage: 'de',
		tags: ['humor', 'intelligenz', 'universum'],
		verified: false,
		authorBio: {
			de: 'Deutsch-schweizerisch-amerikanischer Physiker (1879-1955), Nobelpreisträger.',
			en: 'German-Swiss-American physicist (1879-1955), Nobel laureate.',
		},
	},
	{
		id: 'humor-5',
		text: {
			original: 'In der Kürze liegt die Würze.',
			de: 'In der Kürze liegt die Würze.',
			en: 'Brevity is the soul of wit.',
			it: "La brevità è l'anima dell'arguzia.",
			fr: "La brièveté est l'âme de l'esprit.",
			es: 'La brevedad es el alma del ingenio.',
		},
		author: 'William Shakespeare',
		category: 'humor',
		originalLanguage: 'en',
		source: 'Hamlet',
		year: 1601,
		tags: ['humor', 'kürze', 'sprache'],
		verified: true,
		authorBio: {
			de: 'Englischer Dramatiker und Dichter (1564-1616).',
			en: 'English playwright and poet (1564-1616).',
		},
	},

	// ============================================
	// WISSENSCHAFT
	// ============================================
	{
		id: 'wiss-1',
		text: {
			original: 'Imagination is more important than knowledge.',
			de: 'Vorstellungskraft ist wichtiger als Wissen.',
			en: 'Imagination is more important than knowledge.',
			it: "L'immaginazione è più importante della conoscenza.",
			fr: "L'imagination est plus importante que le savoir.",
			es: 'La imaginación es más importante que el conocimiento.',
		},
		author: 'Albert Einstein',
		category: 'wissenschaft',
		originalLanguage: 'en',
		source: 'Interview, Saturday Evening Post',
		year: 1929,
		tags: ['wissenschaft', 'phantasie', 'wissen'],
		verified: true,
		authorBio: {
			de: 'Deutsch-schweizerisch-amerikanischer Physiker (1879-1955), Nobelpreisträger.',
			en: 'German-Swiss-American physicist (1879-1955), Nobel laureate.',
		},
	},
	{
		id: 'wiss-2',
		text: {
			original: 'Nothing in life is to be feared, it is only to be understood.',
			de: 'Nichts im Leben muss gefürchtet werden, es muss nur verstanden werden.',
			en: 'Nothing in life is to be feared, it is only to be understood.',
			it: "Nulla nella vita va temuto, dev'essere soltanto compreso.",
			fr: "Dans la vie, rien n'est à craindre, tout est à comprendre.",
			es: 'Nada en la vida debe ser temido, solamente comprendido.',
		},
		author: 'Marie Curie',
		category: 'wissenschaft',
		originalLanguage: 'fr',
		tags: ['wissenschaft', 'mut', 'verständnis'],
		verified: true,
		authorBio: {
			de: 'Polnisch-französische Physikerin und Chemikerin (1867-1934), zweifache Nobelpreisträgerin.',
			en: 'Polish-French physicist and chemist (1867-1934), two-time Nobel laureate.',
		},
	},
	{
		id: 'wiss-3',
		text: {
			original:
				'The important thing is not to stop questioning. Curiosity has its own reason for existing.',
			de: 'Das Wichtigste ist, nicht aufzuhören zu fragen. Neugier hat ihre eigene Daseinsberechtigung.',
			en: 'The important thing is not to stop questioning. Curiosity has its own reason for existing.',
			it: 'La cosa importante è non smettere di fare domande. La curiosità ha la sua ragione di esistere.',
			fr: "L'important est de ne pas cesser de questionner. La curiosité a sa propre raison d'exister.",
			es: 'Lo importante es no dejar de hacerse preguntas. La curiosidad tiene su propia razón de existir.',
		},
		author: 'Albert Einstein',
		category: 'wissenschaft',
		originalLanguage: 'en',
		source: 'LIFE Magazine',
		year: 1955,
		tags: ['wissenschaft', 'neugier', 'fragen'],
		verified: true,
	},
	{
		id: 'wiss-4',
		text: {
			original: 'Somewhere, something incredible is waiting to be known.',
			de: 'Irgendwo wartet etwas Unglaubliches darauf, entdeckt zu werden.',
			en: 'Somewhere, something incredible is waiting to be known.',
			it: 'Da qualche parte, qualcosa di incredibile attende di essere scoperto.',
			fr: "Quelque part, quelque chose d'incroyable attend d'être découvert.",
			es: 'En algún lugar, algo increíble está esperando ser descubierto.',
		},
		author: 'Carl Sagan',
		category: 'wissenschaft',
		originalLanguage: 'en',
		tags: ['wissenschaft', 'entdeckung', 'kosmos'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Astrophysiker und Wissenschaftskommunikator (1934-1996).',
			en: 'American astrophysicist and science communicator (1934-1996).',
		},
	},
	{
		id: 'wiss-5',
		text: {
			original: 'One, remember to look up at the stars and not down at your feet.',
			de: 'Erstens: Denkt daran, zu den Sternen aufzublicken und nicht auf eure Füße.',
			en: 'One, remember to look up at the stars and not down at your feet.',
			it: 'Primo: ricordatevi di guardare le stelle e non i vostri piedi.',
			fr: "Premièrement, n'oubliez pas de regarder les étoiles et non vos pieds.",
			es: 'Primero: recuerden mirar las estrellas y no sus pies.',
		},
		author: 'Stephen Hawking',
		category: 'wissenschaft',
		originalLanguage: 'en',
		tags: ['wissenschaft', 'sterne', 'perspektive'],
		verified: true,
		authorBio: {
			de: 'Britischer Physiker und Kosmologe (1942-2018).',
			en: 'British physicist and cosmologist (1942-2018).',
		},
	},

	// ============================================
	// KUNST
	// ============================================
	{
		id: 'kunst-1',
		text: {
			original: 'Every child is an artist. The problem is how to remain an artist once we grow up.',
			de: 'Jedes Kind ist ein Künstler. Das Problem ist, ein Künstler zu bleiben, wenn man erwachsen wird.',
			en: 'Every child is an artist. The problem is how to remain an artist once we grow up.',
			it: 'Ogni bambino è un artista. Il problema è come rimanere un artista quando si cresce.',
			fr: 'Chaque enfant est un artiste. Le problème est de rester un artiste en grandissant.',
			es: 'Todo niño es un artista. El problema es cómo seguir siendo artista cuando se crece.',
		},
		author: 'Pablo Picasso',
		category: 'kunst',
		originalLanguage: 'es',
		tags: ['kunst', 'kreativität', 'kindheit'],
		verified: true,
		authorBio: {
			de: 'Spanischer Maler und Bildhauer (1881-1973), Mitbegründer des Kubismus.',
			en: 'Spanish painter and sculptor (1881-1973), co-founder of Cubism.',
		},
	},
	{
		id: 'kunst-2',
		text: {
			original: 'Art is not what you see, but what you make others see.',
			de: 'Kunst ist nicht das, was du siehst, sondern das, was du andere sehen lässt.',
			en: 'Art is not what you see, but what you make others see.',
			it: "L'arte non è ciò che vedi, ma ciò che fai vedere agli altri.",
			fr: "L'art, ce n'est pas ce que vous voyez, mais ce que vous faites voir aux autres.",
			es: 'El arte no es lo que ves, sino lo que haces ver a los demás.',
		},
		author: 'Edgar Degas',
		category: 'kunst',
		originalLanguage: 'fr',
		tags: ['kunst', 'wahrnehmung', 'perspektive'],
		verified: true,
		authorBio: {
			de: 'Französischer Maler und Bildhauer (1834-1917), Impressionist.',
			en: 'French painter and sculptor (1834-1917), Impressionist.',
		},
	},
	{
		id: 'kunst-3',
		text: {
			original: 'Die Kunst ist eine Vermittlerin des Unaussprechlichen.',
			de: 'Die Kunst ist eine Vermittlerin des Unaussprechlichen.',
			en: 'Art is a mediator of the inexpressible.',
			it: "L'arte è una mediatrice dell'inesprimibile.",
			fr: "L'art est un médiateur de l'inexprimable.",
			es: 'El arte es un mediador de lo inexpresable.',
		},
		author: 'Johann Wolfgang von Goethe',
		category: 'kunst',
		originalLanguage: 'de',
		source: 'Maximen und Reflexionen',
		tags: ['kunst', 'sprache', 'ausdruck'],
		verified: true,
		authorBio: {
			de: 'Deutscher Dichter und Naturforscher (1749-1832).',
			en: 'German poet and naturalist (1749-1832).',
		},
	},
	{
		id: 'kunst-4',
		text: {
			original: 'I dream my painting and I paint my dream.',
			de: 'Ich träume mein Gemälde und male meinen Traum.',
			en: 'I dream my painting and I paint my dream.',
			it: 'Sogno il mio dipinto e dipingo il mio sogno.',
			fr: 'Je rêve ma peinture et je peins mon rêve.',
			es: 'Sueño mi pintura y pinto mi sueño.',
		},
		author: 'Vincent van Gogh',
		category: 'kunst',
		originalLanguage: 'nl',
		tags: ['kunst', 'traum', 'malerei'],
		verified: true,
		authorBio: {
			de: 'Niederländischer Maler (1853-1890), Wegbereiter der modernen Kunst.',
			en: 'Dutch painter (1853-1890), pioneer of modern art.',
		},
	},
	{
		id: 'kunst-5',
		text: {
			original: 'Creativity takes courage.',
			de: 'Kreativität erfordert Mut.',
			en: 'Creativity takes courage.',
			it: 'La creatività richiede coraggio.',
			fr: 'La créativité demande du courage.',
			es: 'La creatividad requiere coraje.',
		},
		author: 'Henri Matisse',
		category: 'kunst',
		originalLanguage: 'fr',
		tags: ['kunst', 'mut', 'kreativität'],
		verified: true,
		authorBio: {
			de: 'Französischer Maler (1869-1954), Wegbereiter des Fauvismus.',
			en: 'French painter (1869-1954), pioneer of Fauvism.',
		},
	},

	// ============================================
	// ZEITGENÖSSISCH (across categories)
	// ============================================
	{
		id: 'zeit-1',
		text: {
			original: "Your time is limited, so don't waste it living someone else's life.",
			de: 'Deine Zeit ist begrenzt, also verschwende sie nicht damit, das Leben eines anderen zu leben.',
			en: "Your time is limited, so don't waste it living someone else's life.",
			it: 'Il tuo tempo è limitato, quindi non sprecarlo vivendo la vita di qualcun altro.',
			fr: "Votre temps est limité, ne le gaspillez pas en vivant la vie de quelqu'un d'autre.",
			es: 'Tu tiempo es limitado, no lo desperdicies viviendo la vida de otra persona.',
		},
		author: 'Steve Jobs',
		category: 'leben',
		originalLanguage: 'en',
		source: 'Stanford Commencement Speech',
		year: 2005,
		tags: ['leben', 'zeit', 'authentizität'],
		verified: true,
	},
	{
		id: 'zeit-2',
		text: {
			original:
				"I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
			de: 'Ich habe gelernt, dass Menschen vergessen, was du gesagt hast, vergessen, was du getan hast, aber nie vergessen, wie du sie fühlen ließest.',
			en: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
			it: 'Ho imparato che le persone dimenticheranno ciò che hai detto, ciò che hai fatto, ma non dimenticheranno mai come le hai fatte sentire.',
			fr: "J'ai appris que les gens oublieront ce que vous avez dit, ce que vous avez fait, mais jamais ce que vous leur avez fait ressentir.",
			es: 'He aprendido que la gente olvidará lo que dijiste, lo que hiciste, pero nunca olvidará cómo les hiciste sentir.',
		},
		author: 'Maya Angelou',
		category: 'weisheit',
		originalLanguage: 'en',
		tags: ['weisheit', 'empathie', 'gefühl'],
		verified: true,
		authorBio: {
			de: 'US-amerikanische Schriftstellerin und Bürgerrechtsaktivistin (1928-2014).',
			en: 'American writer and civil rights activist (1928-2014).',
		},
	},
	{
		id: 'zeit-3',
		text: {
			original: 'Education is the most powerful weapon which you can use to change the world.',
			de: 'Bildung ist die mächtigste Waffe, die du nutzen kannst, um die Welt zu verändern.',
			en: 'Education is the most powerful weapon which you can use to change the world.',
			it: "L'istruzione è l'arma più potente che puoi usare per cambiare il mondo.",
			fr: "L'éducation est l'arme la plus puissante qu'on puisse utiliser pour changer le monde.",
			es: 'La educación es el arma más poderosa que puedes usar para cambiar el mundo.',
		},
		author: 'Nelson Mandela',
		category: 'weisheit',
		originalLanguage: 'en',
		year: 2003,
		tags: ['bildung', 'veränderung', 'welt'],
		verified: true,
		authorBio: {
			de: 'Südafrikanischer Freiheitskämpfer und Staatspräsident (1918-2013), Nobelpreisträger.',
			en: 'South African freedom fighter and president (1918-2013), Nobel laureate.',
		},
	},
	{
		id: 'zeit-4',
		text: {
			original: 'Stay hungry, stay foolish.',
			de: 'Bleibt hungrig, bleibt verrückt.',
			en: 'Stay hungry, stay foolish.',
			it: 'Siate affamati, siate folli.',
			fr: 'Restez affamés, restez fous.',
			es: 'Sigan hambrientos, sigan alocados.',
		},
		author: 'Steve Jobs',
		category: 'motivation',
		originalLanguage: 'en',
		source: 'Stanford Commencement Speech',
		year: 2005,
		tags: ['motivation', 'neugier', 'leidenschaft'],
		verified: true,
	},
	{
		id: 'zeit-5',
		text: {
			original: 'No one can make you feel inferior without your consent.',
			de: 'Niemand kann dir ohne dein Einverständnis das Gefühl geben, minderwertig zu sein.',
			en: 'No one can make you feel inferior without your consent.',
			it: 'Nessuno può farti sentire inferiore senza il tuo consenso.',
			fr: 'Personne ne peut vous faire sentir inférieur sans votre consentement.',
			es: 'Nadie puede hacerte sentir inferior sin tu consentimiento.',
		},
		author: 'Eleanor Roosevelt',
		category: 'mut',
		originalLanguage: 'en',
		tags: ['mut', 'selbstwert', 'stärke'],
		verified: true,
		authorBio: {
			de: 'US-amerikanische Menschenrechtsaktivistin und First Lady (1884-1962).',
			en: 'American human rights activist and First Lady (1884-1962).',
		},
	},
	{
		id: 'zeit-6',
		text: {
			original: 'It is during our darkest moments that we must focus to see the light.',
			de: 'In unseren dunkelsten Momenten müssen wir uns darauf konzentrieren, das Licht zu sehen.',
			en: 'It is during our darkest moments that we must focus to see the light.',
			it: 'È nei nostri momenti più bui che dobbiamo concentrarci per vedere la luce.',
			fr: "C'est dans nos moments les plus sombres que nous devons nous concentrer pour voir la lumière.",
			es: 'Es en nuestros momentos más oscuros que debemos concentrarnos para ver la luz.',
		},
		author: 'Aristoteles',
		category: 'hoffnung',
		originalLanguage: 'el',
		tags: ['hoffnung', 'stärke', 'licht'],
		verified: false,
	},
	{
		id: 'zeit-7',
		text: {
			original: 'The only impossible journey is the one you never begin.',
			de: 'Die einzige unmögliche Reise ist die, die du nie beginnst.',
			en: 'The only impossible journey is the one you never begin.',
			it: "L'unico viaggio impossibile è quello che non inizi mai.",
			fr: 'Le seul voyage impossible est celui que vous ne commencez jamais.',
			es: 'El único viaje imposible es el que nunca comienzas.',
		},
		author: 'Tony Robbins',
		category: 'motivation',
		originalLanguage: 'en',
		tags: ['motivation', 'anfang', 'reise'],
		verified: true,
		authorBio: {
			de: 'US-amerikanischer Motivationsredner und Autor (*1960).',
			en: 'American motivational speaker and author (b. 1960).',
		},
	},
	{
		id: 'zeit-8',
		text: {
			original: 'Think like a queen. A queen is not afraid to fail.',
			de: 'Denke wie eine Königin. Eine Königin hat keine Angst zu scheitern.',
			en: 'Think like a queen. A queen is not afraid to fail.',
			it: 'Pensa come una regina. Una regina non ha paura di fallire.',
			fr: "Pense comme une reine. Une reine n'a pas peur d'échouer.",
			es: 'Piensa como una reina. Una reina no tiene miedo de fracasar.',
		},
		author: 'Oprah Winfrey',
		category: 'mut',
		originalLanguage: 'en',
		tags: ['mut', 'selbstvertrauen', 'frauen'],
		verified: true,
		authorBio: {
			de: 'US-amerikanische Talkshow-Moderatorin und Unternehmerin (*1954).',
			en: 'American talk show host and entrepreneur (b. 1954).',
		},
	},
];

/**
 * Total number of quotes
 */
export const QUOTE_COUNT = QUOTES.length;
