/**
 * Photos module — collection accessors and guest seed data.
 *
 * Uses table names in the unified DB: albums, albumItems, photoFavorites, photoTags, photoMediaTags.
 */

import { db } from '$lib/data/database';
import type { LocalAlbum, LocalAlbumItem, LocalFavorite, LocalTag, LocalPhotoTag } from './types';

// ─── Collection Accessors ──────────────────────────────────

export const albumTable = db.table<LocalAlbum>('albums');
export const albumItemTable = db.table<LocalAlbumItem>('albumItems');
export const photoFavoriteTable = db.table<LocalFavorite>('photoFavorites');
export const photoTagTable = db.table<LocalTag>('photoTags');
export const photoMediaTagTable = db.table<LocalPhotoTag>('photoMediaTags');

// ─── Guest Seed ────────────────────────────────────────────

export const PHOTOS_GUEST_SEED = {
	albums: [
		{
			id: 'album-favorites',
			name: 'Favoriten',
			description: 'Deine Lieblingsfotos an einem Ort.',
			isAutoGenerated: false,
		},
	],
	photoTags: [
		{
			id: 'tag-nature',
			name: 'Natur',
			color: '#22c55e',
		},
		{
			id: 'tag-people',
			name: 'Menschen',
			color: '#3b82f6',
		},
		{
			id: 'tag-travel',
			name: 'Reisen',
			color: '#f59e0b',
		},
	],
};
