<!--
  Photos — Workbench ListView
  Photo albums and recent uploads.
-->
<script lang="ts">
	import { liveQuery } from 'dexie';
	import { db } from '$lib/data/database';
	import type { LocalAlbum, LocalFavorite } from './types';

	let albums = $state<LocalAlbum[]>([]);
	let favorites = $state<LocalFavorite[]>([]);

	$effect(() => {
		const sub = liveQuery(async () => {
			return db
				.table<LocalAlbum>('albums')
				.toArray()
				.then((all) => all.filter((a) => !a.deletedAt));
		}).subscribe((val) => {
			albums = val ?? [];
		});
		return () => sub.unsubscribe();
	});

	$effect(() => {
		const sub = liveQuery(async () => {
			return db
				.table<LocalFavorite>('photoFavorites')
				.toArray()
				.then((all) => all.filter((f) => !f.deletedAt));
		}).subscribe((val) => {
			favorites = val ?? [];
		});
		return () => sub.unsubscribe();
	});
</script>

<div class="flex h-full flex-col gap-3 p-4">
	<div class="flex gap-3 text-xs text-white/40">
		<span>{albums.length} Alben</span>
		<span>{favorites.length} Favoriten</span>
	</div>

	<div class="flex-1 overflow-auto">
		<h3 class="mb-2 text-xs font-medium text-white/50">Alben</h3>
		{#each albums as album (album.id)}
			<div
				class="mb-2 rounded-md border border-white/10 px-3 py-2.5 transition-colors hover:bg-white/5"
			>
				<p class="truncate text-sm font-medium text-white/80">{album.name}</p>
				{#if album.description}
					<p class="mt-1 truncate text-xs text-white/30">{album.description}</p>
				{/if}
				<p class="mt-1 text-xs text-white/40">
					{album.isAutoGenerated ? 'Auto-generiert' : 'Manuell'}
				</p>
			</div>
		{/each}

		{#if albums.length === 0}
			<p class="py-8 text-center text-sm text-white/30">Keine Alben</p>
		{/if}
	</div>
</div>
