/**
 * Photos module types for the unified app.
 */

import type { BaseRecord } from '@manacore/local-store';

export interface LocalAlbum extends BaseRecord {
	name: string;
	description?: string | null;
	coverMediaId?: string | null;
	isAutoGenerated: boolean;
	autoGenerateType?: 'date' | 'location' | 'camera' | null;
	autoGenerateValue?: string | null;
}

export interface LocalAlbumItem extends BaseRecord {
	albumId: string;
	mediaId: string;
	sortOrder: number;
}

export interface LocalFavorite extends BaseRecord {
	mediaId: string;
}

export interface LocalPhotoTag extends BaseRecord {
	mediaId: string;
	tagId: string;
}

/** Server-fetched photo (from mana-media, not local-first). */
export interface Photo {
	id: string;
	url: string;
	thumbnailUrl?: string;
	width?: number;
	height?: number;
	size?: number;
	mimeType?: string;
	isFavorited?: boolean;
	createdAt?: string;
	tags?: Array<{ id: string; name: string; color?: string }>;
	exif?: {
		dateTaken?: string;
		cameraMake?: string;
		cameraModel?: string;
		focalLength?: string;
		aperture?: string;
		iso?: number;
		exposureTime?: string;
		gpsLatitude?: number;
		gpsLongitude?: number;
	};
}

export interface PhotoFilters {
	apps?: string[];
	mimeType?: string;
	dateFrom?: string;
	dateTo?: string;
	hasLocation?: boolean;
	limit?: number;
	offset?: number;
	sortBy?: 'dateTaken' | 'createdAt' | 'size';
	sortOrder?: 'asc' | 'desc';
}

export interface PhotoStats {
	totalCount: number;
	totalSize?: number;
}

/** Album type for UI consumption. */
export interface Album {
	id: string;
	name: string;
	description?: string;
	coverMediaId?: string;
	coverUrl?: string;
	isAutoGenerated: boolean;
	autoGenerateType?: string;
	autoGenerateValue?: string;
	itemCount: number;
	createdAt: string;
	updatedAt: string;
}

export interface AlbumItem {
	id: string;
	albumId: string;
	mediaId: string;
	sortOrder: number;
	addedAt: string;
}
