[build]
  command = "npx expo export --platform web --clear"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

# Umleitung für SPA-Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
